export const allCards = [
  'Abomination',
  'Absorbing Man',
  'Adam Warlock',
  'Aero',
  'Agatha Harkness',
  'Agent 13',
  'Agent Coulson',
  'America Chavez',
  'Angel',
  'Angela',
  'Ant Man',
  'Apocalypse',
  'Armor',
  'Arnim Zola',
  'Baron Mordo',
  'Beast',
  'Bishop',
  'Black Bolt',
  'Black Cat',
  'Black Knight',
  'Black Panther',
  'Black Widow',
  'Blade',
  'Blink',
  'Blob',
  'Blue Marvel',
  'Brood',
  'Bucky Barnes',
  'Bullseye',
  'Cable',
  'Captain America',
  'Captain Marvel',
  'Carnage',
  'Cerebro',
  'Cloak',
  'Colleen Wing',
  'Colossus',
  'Cosmo',
  'Crossbones',
  'Crystal',
  'Cyclops',
  'Dagger',
  'Daredevil',
  'Darkhawk',
  'Dazzler',
  'Deadpool',
  'Death',
  'Deathlok',
  'Debrii',
  'Demon',
  'Destroyer',
  'Devil Dinosaur',
  'Doctor Octopus',
  'Doctor Strange',
  'Domino',
  'DoomBot',
  'Dracula',
  'Drax',
  'Doctor Doom',
  'Drone',
  'Ebony Maw',
  'Electro',
  'Elektra',
  'Elsa Bloodstone',
  'Enchantress',
  'Falcon',
  'Flatman',
  'Forge',
  'Galactus',
  'Gambit',
  'Gamora',
  'Ghost Rider',
  'Ghost-Spider',
  'Giganto',
  'Goblin Queen',
  'Goose',
  'Green Goblin',
  'Groot',
  'Gwenpool',
  'Hawkeye',
  'Hazmat',
  'Heimdall',
  'Hela',
  'Helicarrier',
  'Hellcow',
  'Hit-Monkey',
  'Hobgoblin',
  'The Hood',
  'Hulk',
  'Hulkbuster',
  'Human Torch',
  'Iceman',
  'The Infinaut',
  'Invisible Woman',
  'Iron Fist',
  'Ironheart',
  'Iron Man',
  'Jane Foster Mighty Thor',
  'Jean Grey',
  'Jeff the Baby Land Shark',
  'Jessica Jones',
  'Jubilee',
  'Juggernaut',
  'Kang',
  'Ka-Zar',
  'Killmonger',
  'King Eitri',
  'Kingpin',
  'Kitty Pryde',
  'Klaw',
  'Korg',
  'Kraven',
  'Lady Deathstrike',
  'Lady Sif',
  'Leader',
  'Leech',
  'Legion',
  'The Living Tribunal',
  'Lizard',
  'Lockjaw',
  'Loki',
  'Luke Cage',
  'Magik',
  'Magneto',
  'Makkari',
  'Mantis',
  'Maria Hill',
  'Master Mold',
  'Maximus',
  "M'Baku",
  'Medusa',
  'Mephisto',
  'Miles Morales',
  'Mind Stone',
  'Mirage',
  'Misty Knight',
  'Mjolnir',
  'M.O.D.O.K.',
  'Mojo',
  'Monster',
  'Moon Girl',
  'Moon Knight',
  'Morbius',
  'Morph',
  'Mister Fantastic',
  'Mister Negative',
  'Mister Sinister',
  'Ms. Marvel',
  'Multiple Man',
  'Mysterio',
  'Illusion!',
  'Mystique',
  'Nakia',
  'Namor',
  'Nebula',
  'Negasonic Teenage Warhead',
  'Nick Fury',
  'Nightcrawler',
  'Night Nurse',
  'Ninja',
  'Nova',
  'Odin',
  'Okoye',
  'Omega Red',
  'Onslaught',
  'Orka',
  'Patriot',
  'Polaris',
  'Power Stone',
  'Professor X',
  'Psylocke',
  'Punisher',
  'Quake',
  'Quicksilver',
  'Quinjet',
  'Random',
  'Raptor',
  'Reality Stone',
  'Red Guardian',
  'Red Skull',
  'Rescue',
  'Rhino',
  'Rock',
  'Rocket Raccoon',
  'Rockslide',
  'Rogue',
  'Ronan the Accuser',
  'Sabretooth',
  'Sandman',
  'Sauron',
  'Scarlet Witch',
  'Scorpion',
  'Sentinel',
  'Sentry',
  'Sera',
  'Shadow King',
  'Shang-Chi',
  'Shanna',
  'She-Hulk',
  'Shocker',
  'Shuri',
  'Silk',
  'Silver Sable',
  'Silver Samurai',
  'Silver Surfer',
  'Snowguard',
  'Soul Stone',
  'Space Stone',
  'Spectrum',
  'Spider-Man',
  'Spider-Woman',
  'Squirrel Girl',
  'Star-Lord',
  'Storm',
  'Strong Guy',
  'Stryfe',
  'Sunspot',
  'Super-Skrull',
  'Surtur',
  'Swarm',
  'Sword Master',
  'Taskmaster',
  'Test Card',
  'Thanos',
  'The Collector',
  'Phoenix Force',
  'The Thing',
  'The Void',
  'Thor',
  'Tiger Spirit',
  'Time Stone',
  'Titania',
  'Toad',
  'Typhoid Mary',
  'Uatu the Watcher',
  'Ultron',
  'Uncle Ben',
  'Valkyrie',
  'Venom',
  'Viper',
  'Vision',
  'Viv Vision',
  'Vulture',
  'War Machine',
  'Warpath',
  'Wasp',
  'Wave',
  "Widow's Bite",
  'White Queen',
  'White Tiger',
  'Winter Soldier',
  'Witchfire',
  'Wolfsbane',
  'Wolverine',
  'Wong',
  'X-23',
  'Yellowjacket',
  'Yondu',
  'Yo-Yo',
  'Zabu',
  'Zero',
  'Bast',
  'Attuma',
  'Vibranium',
  'Knull',
  'Symbiote',
  'Stature',
  'Ghost',
  'Nimrod',
  'J. Jonah Jameson',
  'Stegron',
  'Howard the Duck',
  'High Evolutionary',
  'Iron Lad',
  'Spider-Ham',
  'Spider-Man 2099',
  'Echo',
  'Daken',
  'Muramasa Shard',
  'Ravonna Renslayer',
  'Mobius M. Mobius',
  'Alioth',
  'Man-Thing',
  'Ebony Blade',
  'Nico Minoru',
  'Werewolf By Night',
];
