export const allCards = {
  'Abomination': {
    defId: 'Abomination',
    cost: 5,
    power: 9,
    name: 'Abomination',
    description: '<i>"Foolish rabble! You are beneath me!"</i>',
  },
  'Absorbing Man': {
    defId: 'AbsorbingMan',
    cost: 4,
    power: 5,
    name: 'Absorbing Man',
    description:
      "<b>On Reveal:</b> If the last card you played has an <b>On Reveal</b>, copy its text. <i>(if it's in play)</i>",
  },
  'Adam Warlock': {
    defId: 'AdamWarlock',
    cost: 2,
    power: 0,
    name: 'Adam Warlock',
    description: 'At the end of each turn, if you are winning this location, draw a card.',
  },
  'Aero': {
    defId: 'Aero',
    cost: 5,
    power: 8,
    name: 'Aero',
    description: '<b>On Reveal:</b> Move the last enemy card played this turn to this location.',
  },
  'Agatha Harkness': {
    defId: 'AgathaHarkness',
    cost: 6,
    power: 14,
    name: 'Agatha Harkness',
    description: 'Agatha starts in your hand and plays your cards for you.',
  },
  'Agent 13': {
    defId: 'Agent13',
    cost: 1,
    power: 2,
    name: 'Agent 13',
    description: '<b>On Reveal:</b> Add a random card to your hand.',
  },
  'Agent Coulson': {
    defId: 'AgentCoulson',
    cost: 3,
    power: 4,
    name: 'Agent Coulson',
    description: '<b>On Reveal:</b> Add a random 4-Cost and 5-Cost card to your hand.',
  },
  'America Chavez': {
    defId: 'AmericaChavez',
    cost: 6,
    power: 9,
    name: 'America Chavez',
    description: 'Starts on the bottom of your deck. Draw this on turn 6.',
  },
  'Angel': {
    defId: 'Angel',
    cost: 1,
    power: 2,
    name: 'Angel',
    description: 'When one of your cards is destroyed, this flies out of your deck to replace it.',
  },
  'Angela': {
    defId: 'Angela',
    cost: 2,
    power: 0,
    name: 'Angela',
    description: 'After you play a card here,\n+2 Power.',
  },
  'Ant Man': {
    defId: 'AntMan',
    cost: 1,
    power: 1,
    name: 'Ant Man',
    description: '<b>Ongoing:</b> If you have 3 other cards here, +3 Power.',
  },
  'Apocalypse': {
    defId: 'Apocalypse',
    cost: 6,
    power: 8,
    name: 'Apocalypse',
    description: 'When you discard this from your hand, put it back with +4 Power.',
  },
  'Armor': {
    defId: 'Armor',
    cost: 2,
    power: 3,
    name: 'Armor',
    description: "<b>Ongoing:</b> Cards at this location can't be destroyed.",
  },
  'Arnim Zola': {
    defId: 'ArnimZola',
    cost: 6,
    power: 0,
    name: 'Arnim Zola',
    description:
      '<b>On Reveal:</b> Destroy a random friendly card here. Add copies of it to the other locations.',
  },
  'Baron Mordo': {
    defId: 'BaronMordo',
    cost: 2,
    power: 3,
    name: 'Baron Mordo',
    description: '<b>On Reveal:</b> Your opponent draws a card. Set its Cost to 6.',
  },
  'Beast': {
    defId: 'Beast',
    cost: 3,
    power: 4,
    name: 'Beast',
    description:
      '<b>On Reveal:</b> Return your other cards at this location to your hand.\nThey cost 1 less.',
  },
  'Bishop': {
    defId: 'Bishop',
    cost: 3,
    power: 1,
    name: 'Bishop',
    description: 'After you play a card, this gains +1 Power.',
  },
  'Black Bolt': {
    defId: 'BlackBolt',
    cost: 5,
    power: 7,
    name: 'Black Bolt',
    description: "<b>On Reveal:</b> Discard the lowest-cost card from your opponent's hand.",
  },
  'Black Cat': {
    defId: 'BlackCat',
    cost: 3,
    power: 7,
    name: 'Black Cat',
    description: 'If you end the turn with this in your hand, discard it.',
  },
  'Black Knight': {
    defId: 'BlackKnight',
    cost: 1,
    power: 2,
    name: 'Black Knight',
    description: 'When this is destroyed, draw a card.',
  },
  'Black Panther': {
    defId: 'BlackPanther',
    cost: 5,
    power: 4,
    name: 'Black Panther',
    description: "<b>On Reveal:</b> Double this\ncard's Power.",
  },
  'Black Widow': {
    defId: 'BlackWidow',
    cost: 2,
    power: 1,
    name: 'Black Widow',
    description: "<b>On Reveal:</b> Add a Widow's Bite to your opponent's hand.",
  },
  'Blade': {
    defId: 'Blade',
    cost: 1,
    power: 3,
    name: 'Blade',
    description: '<b>On Reveal:</b> Discard a card from your hand.',
  },
  'Blink': {
    defId: 'Blink',
    cost: 3,
    power: 1,
    name: 'Blink',
    description: 'You can move this each turn. When it moves, +1 Power.',
  },
  'Blob': {
    defId: 'Blob',
    cost: 3,
    power: 4,
    name: 'Blob',
    description: '<b>Ongoing:</b> Nothing can move this to another location.',
  },
  'Blue Marvel': {
    defId: 'BlueMarvel',
    cost: 5,
    power: 3,
    name: 'Blue Marvel',
    description: '<b>Ongoing:</b> Your other cards have +1 Power.',
  },
  'Brood': {
    defId: 'Brood',
    cost: 3,
    power: 2,
    name: 'Brood',
    description: '<b>On Reveal:</b> Add 2 Broodlings to this location with the same Power.',
  },
  'Bucky Barnes': {
    defId: 'BuckyBarnes',
    cost: 2,
    power: 1,
    name: 'Bucky Barnes',
    description: 'When this is destroyed, replace it with the Winter Soldier.',
  },
  'Bullseye': {
    defId: 'Bullseye',
    cost: 1,
    power: 2,
    name: 'Bullseye',
    description:
      '<b>On Reveal:</b> The next card you draw will be a 2-Cost card. <i>(if any are left)</i>',
  },
  'Cable': {
    defId: 'Cable',
    cost: 2,
    power: 2,
    name: 'Cable',
    description: "<b>On Reveal:</b> Draw the top card of your opponent's deck.",
  },
  'Captain America': {
    defId: 'CaptainAmerica',
    cost: 3,
    power: 3,
    name: 'Captain America',
    description: '<b>Ongoing:</b> Your other cards at this location have +1 Power.',
  },
  'Captain Marvel': {
    defId: 'CaptainMarvel',
    cost: 4,
    power: 4,
    name: 'Captain Marvel',
    description:
      'At the end of the game, move to a location that wins you the\ngame. (If possible)',
  },
  'Carnage': {
    defId: 'Carnage',
    cost: 2,
    power: 2,
    name: 'Carnage',
    description: '<b>On Reveal:</b> Destroy your other cards here. +2 Power for each destroyed.',
  },
  'Cerebro': {
    defId: 'Cerebro',
    cost: 3,
    power: 0,
    name: 'Cerebro',
    description: '<b>Ongoing:</b> Your highest-Power cards have +2 Power.',
  },
  'Cloak': {
    defId: 'Cloak',
    cost: 2,
    power: 4,
    name: 'Cloak',
    description: '<b>On Reveal:</b> Next turn, both players can move cards to this location.',
  },
  'Colleen Wing': {
    defId: 'ColleenWing',
    cost: 2,
    power: 4,
    name: 'Colleen Wing',
    description: '<b>On Reveal:</b> Discard the lowest-cost card from your hand.',
  },
  'Colossus': {
    defId: 'Colossus',
    cost: 2,
    power: 3,
    name: 'Colossus',
    description: "<b>Ongoing:</b> Can't be destroyed, moved, or have its Power reduced.",
  },
  'Cosmo': {
    defId: 'Cosmo',
    cost: 3,
    power: 3,
    name: 'Cosmo',
    description: "<b>Ongoing:</b> <b>On Reveal</b> abilities won't happen at this location.",
  },
  'Crossbones': {
    defId: 'Crossbones',
    cost: 4,
    power: 8,
    name: 'Crossbones',
    description: 'You can only play this at locations where you are winning.',
  },
  'Crystal': {
    defId: 'Crystal',
    cost: 3,
    power: 3,
    name: 'Crystal',
    description: '<b>On Reveal:</b> Each player\ndraws a card.',
  },
  'Cyclops': {
    defId: 'Cyclops',
    cost: 3,
    power: 4,
    name: 'Cyclops',
    description: '<i>"Let\'s move, X-Men."</i>',
  },
  'Dagger': {
    defId: 'Dagger',
    cost: 2,
    power: 2,
    name: 'Dagger',
    description: 'When this moves to a location,\n+2 Power for each card your\nopponent has there.',
  },
  'Daredevil': {
    defId: 'Daredevil',
    cost: 2,
    power: 2,
    name: 'Daredevil',
    description: "On turn 5, you get to see your opponent's plays before you\nmake your own.",
  },
  'Darkhawk': {
    defId: 'Darkhawk',
    cost: 4,
    power: 0,
    name: 'Darkhawk',
    description: "<b>Ongoing:</b> +2 Power for each card in your opponent's deck.",
  },
  'Dazzler': {
    defId: 'Dazzler',
    cost: 3,
    power: 2,
    name: 'Dazzler',
    description: "<b>Ongoing:</b> +2 Power for each location that's full on your side.",
  },
  'Deadpool': {
    defId: 'Deadpool',
    cost: 1,
    power: 1,
    name: 'Deadpool',
    description: 'When this is destroyed, return it to your hand with double the Power.',
  },
  'Death': {
    defId: 'Death',
    cost: 8,
    power: 12,
    name: 'Death',
    description: 'Costs 1 less for each card destroyed this game.',
  },
  'Deathlok': {
    defId: 'Deathlok',
    cost: 3,
    power: 5,
    name: 'Deathlok',
    description: '<b>On Reveal:</b> Destroy your other cards at this location.',
  },
  'Debrii': {
    defId: 'Debrii',
    cost: 3,
    power: 3,
    name: 'Debrii',
    description: '<b>On Reveal:</b> Add a Rock to each other location, for both players.',
  },
  'Demon': {
    defId: 'Demon',
    cost: 1,
    power: 6,
    name: 'Demon',
    description: '<i>"A deal is a deal."</i>',
  },
  'Destroyer': {
    defId: 'Destroyer',
    cost: 6,
    power: 15,
    name: 'Destroyer',
    description: '<b>On Reveal:</b> Destroy your\nother cards.',
  },
  'Devil Dinosaur': {
    defId: 'DevilDinosaur',
    cost: 5,
    power: 3,
    name: 'Devil Dinosaur',
    description: '<b>Ongoing:</b> +2 Power for each card in your hand.',
  },
  'Doctor Octopus': {
    defId: 'DoctorOctopus',
    cost: 5,
    power: 10,
    name: 'Doctor Octopus',
    description:
      "<b>On Reveal:</b> Pull 4 random cards from your opponent's hand to their side\nof this location.",
  },
  'Doctor Strange': {
    defId: 'DoctorStrange',
    cost: 3,
    power: 3,
    name: 'Doctor Strange',
    description: '<b>On Reveal:</b> Move your highest-Power card(s) to this location.',
  },
  'Domino': {
    defId: 'Domino',
    cost: 2,
    power: 3,
    name: 'Domino',
    description: 'You always draw this card on turn 2, and not before.',
  },
  'DoomBot': {
    defId: 'DoomBot',
    cost: 6,
    power: 5,
    name: 'DoomBot',
    description: '<i>"Doom is supreme!"</i>',
  },
  'Dracula': {
    defId: 'Dracula',
    cost: 4,
    power: 0,
    name: 'Dracula',
    description: 'At the end of the game, discard a card from your hand. This has its Power.',
  },
  'Drax': {
    defId: 'Drax',
    cost: 4,
    power: 6,
    name: 'Drax',
    description: '<b>On Reveal:</b> If your opponent played a card here this turn, +2 Power.',
  },
  'Doctor Doom': {
    defId: 'DrDoom',
    cost: 6,
    power: 5,
    name: 'Doctor Doom',
    description: '<b>On Reveal:</b> Add a 5-Power DoomBot to each other location.',
  },
  'Drone': {
    defId: 'Drone',
    cost: 1,
    power: 1,
    name: 'Drone',
    description: '<i>"zzzzzzZZZTT!"</i>',
  },
  'Ebony Maw': {
    defId: 'EbonyMaw',
    cost: 1,
    power: 7,
    name: 'Ebony Maw',
    description: "You can't play this after turn 3.\n<b>Ongoing:</b> You can't play cards here.",
  },
  'Electro': {
    defId: 'Electro',
    cost: 3,
    power: 2,
    name: 'Electro',
    description:
      '<b>On Reveal:</b> +1 Max Energy. <b>Ongoing:</b> You can only play\n1 card a turn.',
  },
  'Elektra': {
    defId: 'Elektra',
    cost: 1,
    power: 1,
    name: 'Elektra',
    description: '<b>On Reveal:</b> Destroy a random enemy 1-Cost card at this location.',
  },
  'Elsa Bloodstone': {
    defId: 'ElsaBloodstone',
    cost: 1,
    power: 1,
    name: 'Elsa Bloodstone',
    description: 'At the end of each turn, if you are winning this location, +1 Power.',
  },
  'Enchantress': {
    defId: 'Enchantress',
    cost: 4,
    power: 5,
    name: 'Enchantress',
    description:
      '<b>On Reveal:</b> Remove the abilities from all <b>Ongoing</b> cards at this location.',
  },
  'Falcon': {
    defId: 'Falcon',
    cost: 2,
    power: 3,
    name: 'Falcon',
    description: '<b>On Reveal:</b> Return your 1-Cost cards to your hand.',
  },
  'Flatman': {
    defId: 'Flatman',
    cost: 2,
    power: 2,
    name: 'Flatman',
    description: '<b>Ongoing:</b> Adjacent locations have +1 Power.',
  },
  'Forge': {
    defId: 'Forge',
    cost: 2,
    power: 1,
    name: 'Forge',
    description: '<b>On Reveal:</b> Give the next card you play +3 Power.',
  },
  'Galactus': {
    defId: 'Galactus',
    cost: 6,
    power: 7,
    name: 'Galactus',
    description:
      "<b>On Reveal:</b> If you're winning this location and this is your only card here, destroy all other locations.",
  },
  'Gambit': {
    defId: 'Gambit',
    cost: 3,
    power: 3,
    name: 'Gambit',
    description: '<b>On Reveal:</b> Discard a card from your hand. Destroy a random enemy card.',
  },
  'Gamora': {
    defId: 'Gamora',
    cost: 5,
    power: 7,
    name: 'Gamora',
    description: '<b>On Reveal:</b> If your opponent played a card here this turn, +5 Power.',
  },
  'Ghost Rider': {
    defId: 'GhostRider',
    cost: 4,
    power: 3,
    name: 'Ghost Rider',
    description: '<b>On Reveal:</b> Bring back one of your discarded cards to this location.',
  },
  'Ghost-Spider': {
    defId: 'GhostSpider',
    cost: 1,
    power: 2,
    name: 'Ghost-Spider',
    description: '<b>On Reveal:</b> The last card you played moves here.',
  },
  'Giganto': {
    defId: 'Giganto',
    cost: 6,
    power: 14,
    name: 'Giganto',
    description: 'You can only play this at the left location.',
  },
  'Goblin Queen': {
    defId: 'GoblinQueen',
    cost: 2,
    power: 3,
    name: 'Goblin Queen',
    description: "<b>On Reveal:</b> Other cards can't be revealed this turn.",
  },
  'Goose': {
    defId: 'Goose',
    cost: 2,
    power: 2,
    name: 'Goose',
    description: '<b>Ongoing:</b> Nobody can play cards that cost 4, 5, or 6 at this location.',
  },
  'Green Goblin': {
    defId: 'GreenGoblin',
    cost: 3,
    power: -3,
    name: 'Green Goblin',
    description: '<b>On Reveal:</b> Your opponent gains control of this.',
  },
  'Groot': {
    defId: 'Groot',
    cost: 3,
    power: 4,
    name: 'Groot',
    description: '<b>On Reveal:</b> If your opponent played a card here this turn, +2 Power.',
  },
  'Gwenpool': {
    defId: 'Gwenpool',
    cost: 2,
    power: 1,
    name: 'Gwenpool',
    description: "<b>On Reveal:</b> Double this card's Power.",
  },
  'Hawkeye': {
    defId: 'Hawkeye',
    cost: 1,
    power: 1,
    name: 'Hawkeye',
    description: '<b>On Reveal:</b> If you play a card here next turn, +3 Power.',
  },
  'Hazmat': {
    defId: 'Hazmat',
    cost: 2,
    power: 2,
    name: 'Hazmat',
    description: '<b>On Reveal:</b> Afflict all other cards with -1 Power.',
  },
  'Heimdall': {
    defId: 'Heimdall',
    cost: 6,
    power: 8,
    name: 'Heimdall',
    description: '<b>On Reveal:</b> Move your other cards one location to the left.',
  },
  'Hela': {
    defId: 'Hela',
    cost: 6,
    power: 6,
    name: 'Hela',
    description:
      '<b>On Reveal:</b> Resurrect all cards you discarded from your hand to\nrandom locations.',
  },
  'Helicarrier': {
    defId: 'Helicarrier',
    cost: 6,
    power: 10,
    name: 'Helicarrier',
    description: 'When you discard this from your hand, add 3 random cards\nto your hand.',
  },
  'Hellcow': {
    defId: 'Hellcow',
    cost: 4,
    power: 6,
    name: 'Hellcow',
    description: '<b>On Reveal:</b> Discard 2 cards from your hand.',
  },
  'Hit-Monkey': {
    defId: 'HitMonkey',
    cost: 3,
    power: 2,
    name: 'Hit-Monkey',
    description: '<b>On Reveal:</b> Gain +2 Power for each other card you played this turn.',
  },
  'Hobgoblin': {
    defId: 'Hobgoblin',
    cost: 5,
    power: -8,
    name: 'Hobgoblin',
    description: '<b>On Reveal:</b> Your opponent gains control of this.',
  },
  'The Hood': {
    defId: 'Hood',
    cost: 1,
    power: -3,
    name: 'The Hood',
    description: '<b>On Reveal:</b> Add a Demon to your hand.',
  },
  'Hulk': { defId: 'Hulk', cost: 6, power: 12, name: 'Hulk', description: '<i>"HULK SMASH!"</i>' },
  'Hulkbuster': {
    defId: 'Hulkbuster',
    cost: 3,
    power: 5,
    name: 'Hulkbuster',
    description: '<b>On Reveal:</b> Merge this card with a random friendly card at this location.',
  },
  'Human Torch': {
    defId: 'HumanTorch',
    cost: 1,
    power: 2,
    name: 'Human Torch',
    description: 'When this moves, double\nits Power.',
  },
  'Iceman': {
    defId: 'Iceman',
    cost: 1,
    power: 2,
    name: 'Iceman',
    description:
      "<b>On Reveal:</b> Give a random card in your opponent's hand +1 Cost. <i>(maximum 6)</i>",
  },
  'The Infinaut': {
    defId: 'Infinaut',
    cost: 6,
    power: 20,
    name: 'The Infinaut',
    description: "If you played a card last turn, you can't play this.",
  },
  'Invisible Woman': {
    defId: 'InvisibleWoman',
    cost: 2,
    power: 3,
    name: 'Invisible Woman',
    description: '<b>Ongoing:</b> Cards you play here are not revealed until the game ends.',
  },
  'Iron Fist': {
    defId: 'IronFist',
    cost: 1,
    power: 2,
    name: 'Iron Fist',
    description:
      '<b>On Reveal:</b> After you play your next card, move it one location to the left.',
  },
  'Ironheart': {
    defId: 'Ironheart',
    cost: 3,
    power: 0,
    name: 'Ironheart',
    description: '<b>On Reveal:</b> Give 3 other friendly cards +2 Power.',
  },
  'Iron Man': {
    defId: 'IronMan',
    cost: 5,
    power: 0,
    name: 'Iron Man',
    description: '<b>Ongoing:</b> Your total Power is doubled at this location.',
  },
  'Jane Foster Mighty Thor': {
    defId: 'JaneFoster',
    cost: 5,
    power: 8,
    name: 'Jane Foster Mighty Thor',
    description: '<b>On Reveal:</b> Draw all cards that Cost 0 from your deck.',
  },
  'Jean Grey': {
    defId: 'JeanGrey',
    cost: 3,
    power: 3,
    name: 'Jean Grey',
    description:
      '<b>Ongoing:</b> Players must play their first card here each turn. <i>(if possible)</i>',
  },
  'Jeff the Baby Land Shark': {
    defId: 'JeffTheBabyLandShark',
    cost: 2,
    power: 3,
    name: 'Jeff the Baby Land Shark',
    description:
      'You can move this once. Nothing can stop you from moving or playing this to any location.',
  },
  'Jessica Jones': {
    defId: 'JessicaJones',
    cost: 4,
    power: 4,
    name: 'Jessica Jones',
    description: "<b>On Reveal:</b> If you don't play a card here next turn, +4 Power.",
  },
  'Jubilee': {
    defId: 'Jubilee',
    cost: 4,
    power: 1,
    name: 'Jubilee',
    description: '<b>On Reveal:</b> Add the top card of your deck to this location.',
  },
  'Juggernaut': {
    defId: 'Juggernaut',
    cost: 3,
    power: 3,
    name: 'Juggernaut',
    description:
      '<b>On Reveal:</b> If your opponent played cards here this turn, move\nthem randomly.',
  },
  'Kang': {
    defId: 'Kang',
    cost: 5,
    power: 0,
    name: 'Kang',
    description:
      '<b>On Reveal:</b> Look at what your opponent did, then restart the turn. <i>(without Kang)</i>',
  },
  'Ka-Zar': {
    defId: 'KaZar',
    cost: 4,
    power: 4,
    name: 'Ka-Zar',
    description: '<b>Ongoing:</b> Your 1-Cost cards have +1 Power.',
  },
  'Killmonger': {
    defId: 'Killmonger',
    cost: 3,
    power: 3,
    name: 'Killmonger',
    description: '<b>On Reveal:</b> Destroy ALL\n1-Cost cards.',
  },
  'King Eitri': {
    defId: 'KingEitri',
    cost: 5,
    power: 3,
    name: 'King Eitri',
    description: '<b>On Reveal:</b> Give the next card you play +4 Power.',
  },
  'Kingpin': {
    defId: 'Kingpin',
    cost: 3,
    power: 4,
    name: 'Kingpin',
    description: 'When a card moves here on turn 6, destroy it.',
  },
  'Kitty Pryde': {
    defId: 'KittyPryde',
    cost: 1,
    power: 2,
    name: 'Kitty Pryde',
    description: 'When this returns to your hand,\n+1 Power. Returns at the start\nof each turn.',
  },
  'Klaw': {
    defId: 'Klaw',
    cost: 5,
    power: 4,
    name: 'Klaw',
    description: '<b>Ongoing:</b> The location to the right has +6 Power.',
  },
  'Korg': {
    defId: 'Korg',
    cost: 1,
    power: 2,
    name: 'Korg',
    description: "<b>On Reveal:</b> Shuffle a Rock into your opponent's deck.",
  },
  'Kraven': {
    defId: 'Kraven',
    cost: 2,
    power: 2,
    name: 'Kraven',
    description: 'When a card moves here, this gains +2 Power.',
  },
  'Lady Deathstrike': {
    defId: 'LadyDeathstrike',
    cost: 5,
    power: 4,
    name: 'Lady Deathstrike',
    description: '<b>On Reveal:</b> Destroy each card here with less Power than this.',
  },
  'Lady Sif': {
    defId: 'LadySif',
    cost: 3,
    power: 4,
    name: 'Lady Sif',
    description: '<b>On Reveal:</b> Discard the highest-cost card from your hand.',
  },
  'Leader': {
    defId: 'Leader',
    cost: 6,
    power: 2,
    name: 'Leader',
    description:
      '<b>On Reveal:</b> Copy the enemy card(s) with the highest Power played this turn, but on your side.',
  },
  'Leech': {
    defId: 'Leech',
    cost: 5,
    power: 3,
    name: 'Leech',
    description:
      "At the start of turn 6, remove all abilities from cards in your\nopponent's hand.",
  },
  'Legion': {
    defId: 'Legion',
    cost: 5,
    power: 7,
    name: 'Legion',
    description: '<b>On Reveal:</b> Replace each other location with this one.',
  },
  'The Living Tribunal': {
    defId: 'LivingTribunal',
    cost: 6,
    power: 9,
    name: 'The Living Tribunal',
    description: '<b>Ongoing:</b> Split your total Power evenly among all locations.',
  },
  'Lizard': {
    defId: 'Lizard',
    cost: 2,
    power: 5,
    name: 'Lizard',
    description: '<b>Ongoing:</b> -4 Power if your opponent has 4 cards here.',
  },
  'Lockjaw': {
    defId: 'Lockjaw',
    cost: 3,
    power: 2,
    name: 'Lockjaw',
    description:
      'After you play a card here, swap it with a card in your deck.\n<i>(once per turn)</i>',
  },
  'Loki': {
    defId: 'Loki',
    cost: 3,
    power: 5,
    name: 'Loki',
    description:
      "<b>On Reveal:</b> Replace your hand with cards from your opponent's starting deck. Give them -1 cost.",
  },
  'Luke Cage': {
    defId: 'LukeCage',
    cost: 2,
    power: 2,
    name: 'Luke Cage',
    description: "<b>Ongoing:</b> Your cards can't have their Power reduced.",
  },
  'Magik': {
    defId: 'Magik',
    cost: 3,
    power: 2,
    name: 'Magik',
    description:
      "<b>On Reveal:</b> Replace this location with 'Limbo'. Doesn't work\nafter turn 5.",
  },
  'Magneto': {
    defId: 'Magneto',
    cost: 6,
    power: 12,
    name: 'Magneto',
    description: '<b>On Reveal:</b> Move all opposing 3 and 4-Cost cards to this location.',
  },
  'Makkari': {
    defId: 'Makkari',
    cost: 0,
    power: 2,
    name: 'Makkari',
    description: 'When you draw this, place it at a random location.',
  },
  'Mantis': {
    defId: 'Mantis',
    cost: 1,
    power: 2,
    name: 'Mantis',
    description:
      '<b>On Reveal:</b> If your opponent played a card here this turn, draw a card\nfrom <i>their</i> deck.',
  },
  'Maria Hill': {
    defId: 'MariaHill',
    cost: 2,
    power: 3,
    name: 'Maria Hill',
    description: '<b>On Reveal:</b> Add a random 1 or 2-Cost card to your hand.',
  },
  'Master Mold': {
    defId: 'MasterMold',
    cost: 2,
    power: 2,
    name: 'Master Mold',
    description: "<b>On Reveal:</b> Add 2 Sentinel to your opponent's hand.",
  },
  'Maximus': {
    defId: 'Maximus',
    cost: 3,
    power: 7,
    name: 'Maximus',
    description: '<b>On Reveal:</b> Your opponent\ndraws 2 cards.',
  },
  "M'Baku": {
    defId: 'MBaku',
    cost: 1,
    power: 2,
    name: "M'Baku",
    description: 'If this is in your deck at the end of the game, it jumps to a random location.',
  },
  'Medusa': {
    defId: 'Medusa',
    cost: 2,
    power: 2,
    name: 'Medusa',
    description: '<b>On Reveal:</b> If this is at the middle location, +3 Power.',
  },
  'Mephisto': {
    defId: 'Mephisto',
    cost: 6,
    power: 0,
    name: 'Mephisto',
    description: 'If you win this game, double your winnings.',
  },
  'Miles Morales': {
    defId: 'MilesMorales',
    cost: 4,
    power: 5,
    name: 'Miles Morales',
    description: 'If a card moved last turn, this costs 1.',
  },
  'Mind Stone': {
    defId: 'MindStone',
    cost: 1,
    power: 1,
    name: 'Mind Stone',
    description: '<b>On Reveal:</b> Draw 2 Stones from your deck.',
  },
  'Mirage': {
    defId: 'Mirage',
    cost: 2,
    power: 2,
    name: 'Mirage',
    description:
      "<b>On Reveal:</b> Copy the lowest-Cost card in your opponent's hand into your hand. Give it +2 Power.",
  },
  'Misty Knight': {
    defId: 'MistyKnight',
    cost: 1,
    power: 2,
    name: 'Misty Knight',
    description: '<i>"We\'ve got to save this city."</i>',
  },
  'Mjolnir': {
    defId: 'Mjolnir',
    cost: 0,
    power: 0,
    name: 'Mjolnir',
    description: '<b>On Reveal:</b> Give Thor +6 Power.',
  },
  'M.O.D.O.K.': {
    defId: 'Modok',
    cost: 5,
    power: 8,
    name: 'M.O.D.O.K.',
    description: '<b>On Reveal:</b> Discard your hand.',
  },
  'Mojo': {
    defId: 'Mojo',
    cost: 2,
    power: 2,
    name: 'Mojo',
    description: '<b>Ongoing:</b> If both players have 4 cards at this location, +6 Power.',
  },
  'Monster': {
    defId: 'Monster',
    cost: 6,
    power: 9,
    name: 'Monster',
    description: '<i>Careful...he likes to mash.</i>',
  },
  'Moon Girl': {
    defId: 'MoonGirl',
    cost: 4,
    power: 4,
    name: 'Moon Girl',
    description: '<b>On Reveal:</b> Duplicate\nyour hand.',
  },
  'Moon Knight': {
    defId: 'MoonKnight',
    cost: 3,
    power: 3,
    name: 'Moon Knight',
    description: "<b>On Reveal:</b> Discard a card from each player's hand.",
  },
  'Morbius': {
    defId: 'Morbius',
    cost: 2,
    power: 0,
    name: 'Morbius',
    description: '<b>Ongoing:</b> +2 Power for each time you discarded a card this game.',
  },
  'Morph': {
    defId: 'Morph',
    cost: 3,
    power: 0,
    name: 'Morph',
    description: "<b>On Reveal:</b> Become a copy of a random card in your opponent's hand.",
  },
  'Mister Fantastic': {
    defId: 'MrFantastic',
    cost: 3,
    power: 2,
    name: 'Mister Fantastic',
    description: '<b>Ongoing:</b> Adjacent locations have +2 Power.',
  },
  'Mister Negative': {
    defId: 'MrNegative',
    cost: 4,
    power: -1,
    name: 'Mister Negative',
    description: '<b>On Reveal:</b> Swap the Power and Cost of all cards in your deck.',
  },
  'Mister Sinister': {
    defId: 'MrSinister',
    cost: 2,
    power: 2,
    name: 'Mister Sinister',
    description: '<b>On Reveal:</b> Add a Sinister Clone to this location with the same Power.',
  },
  'Ms. Marvel': {
    defId: 'MsMarvel',
    cost: 3,
    power: 4,
    name: 'Ms. Marvel',
    description:
      '<b>Ongoing:</b> If this is your only card here, adjacent locations\nhave +5 Power.',
  },
  'Multiple Man': {
    defId: 'MultipleMan',
    cost: 2,
    power: 3,
    name: 'Multiple Man',
    description: 'When this moves, add a copy to the old location.',
  },
  'Mysterio': {
    defId: 'Mysterio',
    cost: 2,
    power: 4,
    name: 'Mysterio',
    description:
      'As you play this, play Illusions to other locations. Disguise this as an Illusion until the game ends.',
  },
  'Illusion!': {
    defId: 'MysterioIllusion',
    cost: 2,
    power: 0,
    name: 'Illusion!',
    description: 'This is a fake Mysterio!',
  },
  'Mystique': {
    defId: 'Mystique',
    cost: 3,
    power: 0,
    name: 'Mystique',
    description:
      "<b>On Reveal:</b> If the last card you played has an <b>Ongoing</b>, copy its text. <i>(if it's in play)</i>",
  },
  'Nakia': {
    defId: 'Nakia',
    cost: 3,
    power: 3,
    name: 'Nakia',
    description: '<b>On Reveal:</b> Give all cards in your hand +1 Power.',
  },
  'Namor': {
    defId: 'Namor',
    cost: 4,
    power: 6,
    name: 'Namor',
    description: '<b>Ongoing:</b> +5 Power if this is your only card here.',
  },
  'Nebula': {
    defId: 'Nebula',
    cost: 1,
    power: 1,
    name: 'Nebula',
    description:
      "Each turn your opponent doesn't play a card here, +2 Power. <i>(except the turn you play this)</i>",
  },
  'Negasonic Teenage Warhead': {
    defId: 'NegasonicTeenageWarhead',
    cost: 3,
    power: 5,
    name: 'Negasonic Teenage Warhead',
    description: 'After ANY card is played here, destroy this card AND that card.',
  },
  'Nick Fury': {
    defId: 'NickFury',
    cost: 4,
    power: 5,
    name: 'Nick Fury',
    description: '<b>On Reveal:</b> Add 3 random\n6-Cost cards to your hand.',
  },
  'Nightcrawler': {
    defId: 'Nightcrawler',
    cost: 1,
    power: 2,
    name: 'Nightcrawler',
    description: 'You can move this once.',
  },
  'Night Nurse': {
    defId: 'NightNurse',
    cost: 2,
    power: 2,
    name: 'Night Nurse',
    description:
      '<b>On Reveal:</b> Add all cards you discarded or destroyed last turn to your hand.',
  },
  'Ninja': {
    defId: 'Ninja',
    cost: 1,
    power: -2,
    name: 'Ninja',
    description: '<i>"I serve the Hand."</i>',
  },
  'Nova': {
    defId: 'Nova',
    cost: 1,
    power: 1,
    name: 'Nova',
    description: 'When this is destroyed, give your cards +1 Power.',
  },
  'Odin': {
    defId: 'Odin',
    cost: 6,
    power: 8,
    name: 'Odin',
    description:
      '<b>On Reveal:</b> Activate the <b>On Reveal</b> abilities of your other cards\nat this location.',
  },
  'Okoye': {
    defId: 'Okoye',
    cost: 2,
    power: 2,
    name: 'Okoye',
    description: '<b>On Reveal:</b> Give every card in your deck +1 Power.',
  },
  'Omega Red': {
    defId: 'OmegaRed',
    cost: 4,
    power: 5,
    name: 'Omega Red',
    description: "<b>Ongoing:</b> If you're ahead by\n10 Power here, +4 Power\nto other locations.",
  },
  'Onslaught': {
    defId: 'Onslaught',
    cost: 6,
    power: 7,
    name: 'Onslaught',
    description: '<b>Ongoing:</b> Double your other <b>Ongoing</b> effects at this location.',
  },
  'Orka': {
    defId: 'Orka',
    cost: 6,
    power: 11,
    name: 'Orka',
    description: '<b>Ongoing:</b> +5 Power if this is your only card here.',
  },
  'Patriot': {
    defId: 'Patriot',
    cost: 3,
    power: 1,
    name: 'Patriot',
    description: '<b>Ongoing:</b> Your cards with no abilities have +2 Power.',
  },
  'Polaris': {
    defId: 'Polaris',
    cost: 3,
    power: 5,
    name: 'Polaris',
    description: '<b>On Reveal:</b> Move an opposing 1 or 2-Cost card to this location.',
  },
  'Power Stone': {
    defId: 'PowerStone',
    cost: 1,
    power: 3,
    name: 'Power Stone',
    description:
      "<b>Ongoing:</b> If you've played all 6 stones, Thanos has +10 Power. <i>(wherever he is)</i>",
  },
  'Professor X': {
    defId: 'ProfessorX',
    cost: 5,
    power: 3,
    name: 'Professor X',
    description:
      "<b>Ongoing:</b> Lock down this location. <i>(Cards can't be added, removed, etc.)</i>",
  },
  'Psylocke': {
    defId: 'Psylocke',
    cost: 2,
    power: 1,
    name: 'Psylocke',
    description: '<b>On Reveal:</b> Next turn, you get +1 Energy.',
  },
  'Punisher': {
    defId: 'Punisher',
    cost: 3,
    power: 2,
    name: 'Punisher',
    description: '<b>Ongoing:</b> +1 Power for each opposing card at this location.',
  },
  'Quake': {
    defId: 'Quake',
    cost: 2,
    power: 3,
    name: 'Quake',
    description:
      '<b>On Reveal:</b> If this is at the middle location, swap the positions of\neach location.',
  },
  'Quicksilver': {
    defId: 'Quicksilver',
    cost: 1,
    power: 2,
    name: 'Quicksilver',
    description: 'Starts in your opening hand.',
  },
  'Quinjet': {
    defId: 'Quinjet',
    cost: 1,
    power: 2,
    name: 'Quinjet',
    description:
      "<b>Ongoing:</b> Cards that didn't start in your deck cost 1 less. <i>(minimum 1)</i>",
  },
  'Random': {
    defId: 'Random',
    cost: 4,
    power: 0,
    name: 'Random',
    description:
      "<b>On Reveal:</b> Set this card's Power equal to the Power of a random card in your deck.",
  },
  'Raptor': {
    defId: 'Raptor',
    cost: 1,
    power: 1,
    name: 'Raptor',
    description: '<i>SCREEEEEEEE</i>',
  },
  'Reality Stone': {
    defId: 'RealityStone',
    cost: 1,
    power: 1,
    name: 'Reality Stone',
    description: '<b>On Reveal:</b> Transform this location into a new one. Draw a card.',
  },
  'Red Guardian': {
    defId: 'RedGuardian',
    cost: 3,
    power: 6,
    name: 'Red Guardian',
    description: '<b>On Reveal:</b> You must play a card here next turn.',
  },
  'Red Skull': {
    defId: 'RedSkull',
    cost: 5,
    power: 14,
    name: 'Red Skull',
    description: '<b>Ongoing:</b> Enemy cards at this location have +2 Power.',
  },
  'Rescue': {
    defId: 'Rescue',
    cost: 4,
    power: 4,
    name: 'Rescue',
    description: '<b>On Reveal:</b> If you play a card here next turn, +5 Power.',
  },
  'Rhino': {
    defId: 'Rhino',
    cost: 3,
    power: 3,
    name: 'Rhino',
    description: '<b>On Reveal:</b> Ruin this location. (remove its ability)',
  },
  'Rock': {
    defId: 'Rock',
    cost: 1,
    power: 0,
    name: 'Rock',
    description: "<i>Well, that's useless....</i>",
  },
  'Rocket Raccoon': {
    defId: 'RocketRaccoon',
    cost: 1,
    power: 2,
    name: 'Rocket Raccoon',
    description: '<b>On Reveal:</b> If your opponent played a card here this turn, +2 Power.',
  },
  'Rockslide': {
    defId: 'Rockslide',
    cost: 3,
    power: 3,
    name: 'Rockslide',
    description: "<b>On Reveal:</b> Shuffle 2 Rocks into your opponent's deck.",
  },
  'Rogue': {
    defId: 'Rogue',
    cost: 3,
    power: 2,
    name: 'Rogue',
    description:
      '<b>On Reveal:</b> Steal an <b>Ongoing</b> ability from a random enemy card at\nthis location.',
  },
  'Ronan the Accuser': {
    defId: 'Ronan',
    cost: 5,
    power: 3,
    name: 'Ronan the Accuser',
    description: "<b>Ongoing:</b> +2 Power for each card in your opponent's hand.",
  },
  'Sabretooth': {
    defId: 'Sabretooth',
    cost: 3,
    power: 4,
    name: 'Sabretooth',
    description: 'When this is destroyed, return it to your hand. It costs 0.',
  },
  'Sandman': {
    defId: 'Sandman',
    cost: 5,
    power: 3,
    name: 'Sandman',
    description: '<b>Ongoing:</b> Players can only play 1 card a turn.',
  },
  'Sauron': {
    defId: 'Sauron',
    cost: 3,
    power: 3,
    name: 'Sauron',
    description:
      '<b>On Reveal:</b> Remove the abilities from all <b>Ongoing</b> cards in your\nhand and deck.',
  },
  'Scarlet Witch': {
    defId: 'ScarletWitch',
    cost: 2,
    power: 3,
    name: 'Scarlet Witch',
    description: '<b>On Reveal:</b> Replace this location with a random new one.',
  },
  'Scorpion': {
    defId: 'Scorpion',
    cost: 2,
    power: 2,
    name: 'Scorpion',
    description: "<b>On Reveal:</b> Afflict cards in your opponent's hand with -1 Power.",
  },
  'Sentinel': {
    defId: 'Sentinel',
    cost: 2,
    power: 3,
    name: 'Sentinel',
    description: '<b>On Reveal:</b> Add another Sentinel to your hand.',
  },
  'Sentry': {
    defId: 'Sentry',
    cost: 4,
    power: 10,
    name: 'Sentry',
    description:
      "You can't play this at the right location.\n<b>On Reveal:</b> Add a -10 Power Void to the right location.",
  },
  'Sera': {
    defId: 'Sera',
    cost: 5,
    power: 4,
    name: 'Sera',
    description: '<b>Ongoing:</b> Cards in your hand cost 1 less. <i>(minimum 1)</i>',
  },
  'Shadow King': {
    defId: 'ShadowKing',
    cost: 3,
    power: 3,
    name: 'Shadow King',
    description: '<b>On Reveal:</b> Set all cards here to their original base Power.',
  },
  'Shang-Chi': {
    defId: 'ShangChi',
    cost: 4,
    power: 3,
    name: 'Shang-Chi',
    description:
      '<b>On Reveal:</b> Destroy all enemy cards at this location that have\n9 or more Power.',
  },
  'Shanna': {
    defId: 'Shanna',
    cost: 3,
    power: 2,
    name: 'Shanna',
    description: '<b>On Reveal:</b> Add a random\n1-Cost card to each location.',
  },
  'She-Hulk': {
    defId: 'SheHulk',
    cost: 6,
    power: 9,
    name: 'She-Hulk',
    description: 'Costs 1 less for each unspent Energy last turn.',
  },
  'Shocker': {
    defId: 'Shocker',
    cost: 2,
    power: 3,
    name: 'Shocker',
    description: '<i>"I\'m gonna blast you!"</i>',
  },
  'Shuri': {
    defId: 'Shuri',
    cost: 4,
    power: 2,
    name: 'Shuri',
    description: '<b>On Reveal:</b> If you play your next card here, double its Power.',
  },
  'Silk': {
    defId: 'Silk',
    cost: 2,
    power: 5,
    name: 'Silk',
    description: 'After ANY card is played here, this moves to another location.',
  },
  'Silver Sable': {
    defId: 'SilverSable',
    cost: 2,
    power: 6,
    name: 'Silver Sable',
    description: 'You can only play this at a location where you have 6+ total Power.',
  },
  'Silver Samurai': {
    defId: 'SilverSamurai',
    cost: 4,
    power: 5,
    name: 'Silver Samurai',
    description: '<b>On Reveal:</b> Each player discards the lowest-Power card from their hand.',
  },
  'Silver Surfer': {
    defId: 'SilverSurfer',
    cost: 3,
    power: 2,
    name: 'Silver Surfer',
    description: '<b>On Reveal:</b> Give your other\n3-Cost cards +2 Power.',
  },
  'Snowguard': {
    defId: 'Snowguard',
    cost: 1,
    power: 2,
    name: 'Snowguard',
    description: 'While in your hand, this transforms each turn into a Hawk or a Bear.',
  },
  'Soul Stone': {
    defId: 'SoulStone',
    cost: 1,
    power: 1,
    name: 'Soul Stone',
    description: '<b>On Reveal:</b> Draw a card. <b>Ongoing:</b> Enemy cards here have -1 Power.',
  },
  'Space Stone': {
    defId: 'SpaceStone',
    cost: 1,
    power: 1,
    name: 'Space Stone',
    description:
      '<b>On Reveal:</b> Next turn, you can move one card to this location. Draw a card.',
  },
  'Spectrum': {
    defId: 'Spectrum',
    cost: 6,
    power: 5,
    name: 'Spectrum',
    description: '<b>On Reveal:</b> Give your <b>Ongoing</b> cards +2 Power.',
  },
  'Spider-Man': {
    defId: 'SpiderMan',
    cost: 3,
    power: 5,
    name: 'Spider-Man',
    description:
      '<b>On Reveal:</b> Move to another location and pull an enemy card from\nhere to there.',
  },
  'Spider-Woman': {
    defId: 'SpiderWoman',
    cost: 5,
    power: 8,
    name: 'Spider-Woman',
    description: '<b>On Reveal:</b> Afflict all enemy cards here with -1 Power.',
  },
  'Squirrel Girl': {
    defId: 'SquirrelGirl',
    cost: 1,
    power: 1,
    name: 'Squirrel Girl',
    description: '<b>On Reveal:</b> Add a 1-Power Squirrel to each other location.',
  },
  'Star-Lord': {
    defId: 'Starlord',
    cost: 2,
    power: 2,
    name: 'Star-Lord',
    description: '<b>On Reveal:</b> If your opponent played a card here this turn, +3 Power.',
  },
  'Storm': {
    defId: 'Storm',
    cost: 3,
    power: 2,
    name: 'Storm',
    description:
      '<b>On Reveal:</b> Flood this location. Next turn is the last turn cards can\nbe played here.',
  },
  'Strong Guy': {
    defId: 'StrongGuy',
    cost: 4,
    power: 4,
    name: 'Strong Guy',
    description: '<b>Ongoing:</b> If your hand is empty, +6 Power.',
  },
  'Stryfe': {
    defId: 'Stryfe',
    cost: 3,
    power: 7,
    name: 'Stryfe',
    description: 'If your opponent has 12+ Power here at the end of any turn, destroy this.',
  },
  'Sunspot': {
    defId: 'Sunspot',
    cost: 1,
    power: 0,
    name: 'Sunspot',
    description: 'At the end of each turn, gain +1 Power for each unspent Energy.',
  },
  'Super-Skrull': {
    defId: 'SuperSkrull',
    cost: 4,
    power: 2,
    name: 'Super-Skrull',
    description: '<b>Ongoing:</b> Has the <b>Ongoing</b> effects of all enemy cards.',
  },
  'Surtur': {
    defId: 'Surtur',
    cost: 5,
    power: 0,
    name: 'Surtur',
    description: 'If you move the Human Torch to this location, +10 Power.',
  },
  'Swarm': {
    defId: 'Swarm',
    cost: 2,
    power: 3,
    name: 'Swarm',
    description: 'When this is discarded from your hand, add two copies that Cost 0\nto your hand.',
  },
  'Sword Master': {
    defId: 'SwordMaster',
    cost: 3,
    power: 6,
    name: 'Sword Master',
    description: '<b>On Reveal:</b> Discard a card from your hand.',
  },
  'Taskmaster': {
    defId: 'Taskmaster',
    cost: 5,
    power: 0,
    name: 'Taskmaster',
    description:
      "<b>On Reveal:</b> Set this card’s Power equal to that of the last card you played. <i>(if that card's in play)</i>",
  },
  'Test Card': { defId: 'TestCard', cost: 4, power: 4, name: 'Test Card', description: 'ERROR' },
  'Thanos': {
    defId: 'Thanos',
    cost: 6,
    power: 10,
    name: 'Thanos',
    description: 'At the start of the game, shuffle the six Infinity Stones into your deck.',
  },
  'The Collector': {
    defId: 'TheCollector',
    cost: 2,
    power: 2,
    name: 'The Collector',
    description: 'When a card enters your hand from anywhere <i>(except your deck)</i>,\n+1 Power.',
  },
  'Phoenix Force': {
    defId: 'ThePhoenixForce',
    cost: 4,
    power: 5,
    name: 'Phoenix Force',
    description:
      '<b>On Reveal:</b> Revive one of your destroyed cards and merge with it. That card can move each turn.',
  },
  'The Thing': {
    defId: 'TheThing',
    cost: 4,
    power: 6,
    name: 'The Thing',
    description: '<i>"It\'s clobberin\' time!"</i>',
  },
  'The Void': {
    defId: 'TheVoid',
    cost: 4,
    power: -10,
    name: 'The Void',
    description: '<i>Hello again...</i>',
  },
  'Thor': {
    defId: 'Thor',
    cost: 3,
    power: 4,
    name: 'Thor',
    description: '<b>On Reveal:</b> Shuffle Mjolnir into your deck.',
  },
  'Tiger Spirit': {
    defId: 'TigerSpirit',
    cost: 5,
    power: 7,
    name: 'Tiger Spirit',
    description: '<i>"Vengeance is mine!"</i>',
  },
  'Time Stone': {
    defId: 'TimeStone',
    cost: 1,
    power: 1,
    name: 'Time Stone',
    description: '<b>On Reveal:</b> Draw a card. Next turn, you get +1 Energy.',
  },
  'Titania': {
    defId: 'Titania',
    cost: 1,
    power: 5,
    name: 'Titania',
    description: 'After ANY card is played here, this card switches sides.',
  },
  'Toad': {
    defId: 'Toad',
    cost: 2,
    power: 3,
    name: 'Toad',
    description: '<b>On Reveal:</b> Move the last card you played to this location.',
  },
  'Typhoid Mary': {
    defId: 'TyphoidMary',
    cost: 4,
    power: 10,
    name: 'Typhoid Mary',
    description: '<b>Ongoing:</b> Your other cards\nhave -1 Power.',
  },
  'Uatu the Watcher': {
    defId: 'Uatu',
    cost: 1,
    power: 2,
    name: 'Uatu the Watcher',
    description: 'Once this is in your hand, you can see the unrevealed locations.',
  },
  'Ultron': {
    defId: 'Ultron',
    cost: 6,
    power: 8,
    name: 'Ultron',
    description: '<b>On Reveal:</b> Create four 1-Power Drones at each other location.',
  },
  'Uncle Ben': {
    defId: 'UncleBen',
    cost: 1,
    power: 2,
    name: 'Uncle Ben',
    description: 'When this card is destroyed, add Spider-Man to your hand.',
  },
  'Valkyrie': {
    defId: 'Valkyrie',
    cost: 5,
    power: 3,
    name: 'Valkyrie',
    description: '<b>On Reveal:</b> Set ALL cards at this location to 3 Power.',
  },
  'Venom': {
    defId: 'Venom',
    cost: 3,
    power: 3,
    name: 'Venom',
    description:
      '<b>On Reveal:</b> Destroy your other cards at this location. Add their Power\nto this card.',
  },
  'Viper': {
    defId: 'Viper',
    cost: 2,
    power: 3,
    name: 'Viper',
    description:
      '<b>On Reveal:</b> Your opponent gains control of one of your other cards\nat this location.',
  },
  'Vision': {
    defId: 'Vision',
    cost: 5,
    power: 8,
    name: 'Vision',
    description: 'You can move this each turn.',
  },
  'Viv Vision': {
    defId: 'Viv',
    cost: 2,
    power: 3,
    name: 'Viv Vision',
    description: 'When you move a card to a location, move this card\nthere as well.',
  },
  'Vulture': {
    defId: 'Vulture',
    cost: 3,
    power: 3,
    name: 'Vulture',
    description: 'When this card moves,\n+5 Power.',
  },
  'War Machine': {
    defId: 'WarMachine',
    cost: 4,
    power: 5,
    name: 'War Machine',
    description: '<b>Ongoing:</b> Your 1-Cost cards have +1 Power.',
  },
  'Warpath': {
    defId: 'Warpath',
    cost: 4,
    power: 5,
    name: 'Warpath',
    description: '<b>Ongoing:</b> If any of your locations are empty, +4 Power.',
  },
  'Wasp': {
    defId: 'Wasp',
    cost: 0,
    power: 1,
    name: 'Wasp',
    description: '<i>"My secret power is that I get things done."</i>',
  },
  'Wave': {
    defId: 'Wave',
    cost: 3,
    power: 3,
    name: 'Wave',
    description: '<b>On Reveal:</b> All cards cost 4 until the end of next turn.',
  },
  "Widow's Bite": {
    defId: 'WidowsBite',
    cost: 0,
    power: 0,
    name: "Widow's Bite",
    description: "While this is in your hand, you can't draw cards.",
  },
  'White Queen': {
    defId: 'WhiteQueen',
    cost: 4,
    power: 6,
    name: 'White Queen',
    description:
      "<b>On Reveal:</b> Copy the highest-Cost card in your opponent's hand\ninto your hand.",
  },
  'White Tiger': {
    defId: 'WhiteTiger',
    cost: 5,
    power: 1,
    name: 'White Tiger',
    description: '<b>On Reveal:</b> Add a 7-Power Tiger to another location.',
  },
  'Winter Soldier': {
    defId: 'WinterSoldier',
    cost: 2,
    power: 6,
    name: 'Winter Soldier',
    description: '<i>"It\'s time for me to face the past."</i>',
  },
  'Witchfire': {
    defId: 'Witchfire',
    cost: 2,
    power: 3,
    name: 'Witchfire',
    description: '<b>On Reveal:</b> Your opponent draws a card, increase its cost by 1.',
  },
  'Wolfsbane': {
    defId: 'Wolfsbane',
    cost: 3,
    power: 1,
    name: 'Wolfsbane',
    description: '<b>On Reveal:</b> +2 Power for each other card you have here.',
  },
  'Wolverine': {
    defId: 'Wolverine',
    cost: 2,
    power: 2,
    name: 'Wolverine',
    description:
      'When this is discarded or destroyed, regenerate it at a random location\nwith +2 Power.',
  },
  'Wong': {
    defId: 'Wong',
    cost: 4,
    power: 2,
    name: 'Wong',
    description: '<b>Ongoing:</b> Your <b>On Reveal</b> abilities at this location happen twice.',
  },
  'X-23': {
    defId: 'X23',
    cost: 1,
    power: 2,
    name: 'X-23',
    description:
      'When this is discarded or destroyed, regenerate it at a random location and you get +1 Energy next turn.',
  },
  'Yellowjacket': {
    defId: 'Yellowjacket',
    cost: 0,
    power: 2,
    name: 'Yellowjacket',
    description: '<b>On Reveal:</b> Afflict your other cards at this location with -1 Power.',
  },
  'Yondu': {
    defId: 'Yondu',
    cost: 1,
    power: 2,
    name: 'Yondu',
    description: "<b>On Reveal:</b> Destroy the top card of your opponent's deck.",
  },
  'Yo-Yo': {
    defId: 'YoYo',
    cost: 1,
    power: 2,
    name: 'Yo-Yo',
    description: 'When this card moves, move it back with +1 Power.',
  },
  'Zabu': {
    defId: 'Zabu',
    cost: 2,
    power: 2,
    name: 'Zabu',
    description: '<b>Ongoing:</b> Your 4-Cost cards cost 1 less. <i>(minimum 1)</i>',
  },
  'Zero': {
    defId: 'Zero',
    cost: 1,
    power: 3,
    name: 'Zero',
    description: '<b>On Reveal:</b> Remove the abilities on the next card you play.',
  },
  'Bast': {
    defId: 'Bast',
    cost: 1,
    power: 1,
    name: 'Bast',
    description: '<b>On Reveal:</b> Set the Power of all cards in your hand to 3.',
  },
  'Attuma': {
    defId: 'Attuma',
    cost: 4,
    power: 10,
    name: 'Attuma',
    description: 'If you have another card here at the end of your turn, destroy this.',
  },
  'Vibranium': {
    defId: 'Vibranium',
    cost: 1,
    power: 4,
    name: 'Vibranium',
    description: "<b>Ongoing:</b> Can't be destroyed.",
  },
  'Knull': {
    defId: 'Knull',
    cost: 6,
    power: 0,
    name: 'Knull',
    description: '<b>Ongoing:</b> Has the combined Power of all cards destroyed this game.',
  },
  'Symbiote': {
    defId: 'Symbiote',
    cost: 4,
    power: 0,
    name: 'Symbiote',
    description: '<i>YUUUUUMMMMMM!!!</i>',
  },
  'Stature': {
    defId: 'Stature',
    cost: 5,
    power: 6,
    name: 'Stature',
    description: 'Costs 1 if your opponent discarded a card from their hand this game.',
  },
  'Ghost': {
    defId: 'Ghost',
    cost: 1,
    power: 2,
    name: 'Ghost',
    description:
      '<b>Ongoing:</b> Your cards are always revealed last. <i>(Their <b>On Reveal</b> abilities happen last.)</i>',
  },
  'Nimrod': {
    defId: 'Nimrod',
    cost: 5,
    power: 6,
    name: 'Nimrod',
    description: 'When this is destroyed, add a copy to each other location.',
  },
  'J. Jonah Jameson': {
    defId: 'JJonahJameson',
    cost: 1,
    power: 1,
    name: 'J. Jonah Jameson',
    description: '<b>Ongoing:</b> Your emotes\nare ruder.',
  },
  'Stegron': {
    defId: 'Stegron',
    cost: 4,
    power: 5,
    name: 'Stegron',
    description: '<b>On Reveal:</b> Move an enemy card from here to another location.',
  },
  'Howard the Duck': {
    defId: 'HowardTheDuck',
    cost: 1,
    power: 2,
    name: 'Howard the Duck',
    description: '<b>Ongoing:</b> Tap this to see the top card of your deck.',
  },
  'High Evolutionary': {
    defId: 'HighEvolutionary',
    cost: 4,
    power: 4,
    name: 'High Evolutionary',
    description: 'At the start of the game, unlock the potential of your cards with no abilities.',
  },
  'Iron Lad': {
    defId: 'IronLad',
    cost: 4,
    power: 6,
    name: 'Iron Lad',
    description: "<b>On Reveal:</b> Copy the text of your deck's top card.",
  },
  'Spider-Ham': {
    defId: 'SpiderHam',
    cost: 2,
    power: 2,
    name: 'Spider-Ham',
    description:
      "<b>On Reveal:</b> Transform the highest-cost card in your opponent's hand into a Pig, keeping its Power and Cost.",
  },
  'Spider-Man 2099': {
    defId: 'SpiderMan2099',
    cost: 4,
    power: 6,
    name: 'Spider-Man 2099',
    description: 'The first time this moves to a location, destroy an enemy card there.',
  },
  'Echo': {
    defId: 'Echo',
    cost: 1,
    power: 2,
    name: 'Echo',
    description: 'After your opponent plays an <b>Ongoing</b> card here, remove its abilities.',
  },
  'Daken': {
    defId: 'Daken',
    cost: 3,
    power: 4,
    name: 'Daken',
    description: '<b>On Reveal:</b> Add the Muramasa Shard to your hand.',
  },
  'Muramasa Shard': {
    defId: 'MuramasaShard',
    cost: 1,
    power: 1,
    name: 'Muramasa Shard',
    description: "When this is discarded or destroyed, double Daken's Power.",
  },
  'Ravonna Renslayer': {
    defId: 'RavonnaRenslayer',
    cost: 3,
    power: 3,
    name: 'Ravonna Renslayer',
    description: '<b>Ongoing:</b> Your cards with 1 or less Power cost 1 less. <i>(minimum 1)</i>',
  },
  'Mobius M. Mobius': {
    defId: 'MobiusMMobius',
    cost: 2,
    power: 3,
    name: 'Mobius M. Mobius',
    description:
      "<b>Ongoing:</b> Your Costs can't be increased. Your opponent's Costs can't be reduced.",
  },
  'Alioth': {
    defId: 'Alioth',
    cost: 6,
    power: 5,
    name: 'Alioth',
    description:
      '<b>On Reveal:</b> Destroy ALL enemy cards played here this turn. <i>(including unrevealed cards)</i>',
  },
  'Man-Thing': { defId: 'ManThing', cost: 4, power: 6, name: 'Man-Thing', description: 'none' },
  'Ebony Blade': {
    defId: 'EbonyBlade',
    cost: 5,
    power: 4,
    name: 'Ebony Blade',
    description:
      '<b>On Reveal:</b> If your Black Knight is here, destroy the highest-Power enemy card(s) here.',
  },
  'Nico Minoru': {
    defId: 'NicoMinoru',
    cost: 3,
    power: 4,
    name: 'Nico Minoru',
    description: 'none',
  },
  'Werewolf By Night': {
    defId: 'WerewolfByNight',
    cost: 0,
    power: 0,
    name: 'Werewolf By Night',
    description: 'none',
  },
} as const;
