export const allTitles = {
  'movies': {
    '1998|Blade': {
      year: '1998',
      title: 'Blade',
      wikipedia: 'https://en.wikipedia.org/wiki/Blade_(1998_film)',
      continuity: 'blade',
    },
    '2000|X-Men': {
      year: '2000',
      title: 'X-Men',
      wikipedia: 'https://en.wikipedia.org/wiki/X-Men_(film)',
      continuity: 'fox-x-men',
    },
    '2002|Blade II': {
      year: '2002',
      title: 'Blade II',
      wikipedia: 'https://en.wikipedia.org/wiki/Blade_II',
      continuity: 'blade',
    },
    '2002|Spider-Man': {
      year: '2002',
      title: 'Spider-Man',
      wikipedia: 'https://en.wikipedia.org/wiki/Spider-Man_(2002_film)',
      continuity: 'tobey-spiderman',
    },
    '2003|Daredevil': {
      year: '2003',
      title: 'Daredevil',
      wikipedia: 'https://en.wikipedia.org/wiki/Daredevil_(film)',
      continuity: 'fox-daredevil',
    },
    '2003|X2': {
      year: '2003',
      title: 'X2',
      wikipedia: 'https://en.wikipedia.org/wiki/X2_(film)',
      continuity: 'fox-x-men',
    },
    '2003|Hulk': {
      year: '2003',
      title: 'Hulk',
      wikipedia: 'https://en.wikipedia.org/wiki/Hulk_(film)',
    },
    '2004|The Punisher': {
      year: '2004',
      title: 'The Punisher',
      wikipedia: 'https://en.wikipedia.org/wiki/The_Punisher_(2004_film)',
    },
    '2004|Spider-Man 2': {
      year: '2004',
      title: 'Spider-Man 2',
      wikipedia: 'https://en.wikipedia.org/wiki/Spider-Man_2',
      continuity: 'tobey-spiderman',
    },
    '2004|Blade: Trinity': {
      year: '2004',
      title: 'Blade: Trinity',
      wikipedia: 'https://en.wikipedia.org/wiki/Blade:_Trinity',
      continuity: 'blade',
    },
    '2005|Elektra': {
      year: '2005',
      title: 'Elektra',
      wikipedia: 'https://en.wikipedia.org/wiki/Elektra_(2005_film)',
      continuity: 'fox-daredevil',
    },
    '2005|Fantastic Four': {
      year: '2005',
      title: 'Fantastic Four',
      wikipedia: 'https://en.wikipedia.org/wiki/Fantastic_Four_(2005_film)',
      continuity: 'fox-fantastic-four',
    },
    '2006|X-Men: The Last Stand': {
      year: '2006',
      title: 'X-Men: The Last Stand',
      wikipedia: 'https://en.wikipedia.org/wiki/X-Men:_The_Last_Stand',
      continuity: 'fox-x-men',
    },
    '2007|Ghost Rider': {
      year: '2007',
      title: 'Ghost Rider',
      wikipedia: 'https://en.wikipedia.org/wiki/Ghost_Rider_(2007_film)',
      continuity: 'sony-ghost-rider',
    },
    '2007|Spider-Man 3': {
      year: '2007',
      title: 'Spider-Man 3',
      wikipedia: 'https://en.wikipedia.org/wiki/Spider-Man_3',
      continuity: 'tobey-spiderman',
    },
    '2007|Fantastic Four: Rise of the Silver Surfer': {
      year: '2007',
      title: 'Fantastic Four: Rise of the Silver Surfer',
      wikipedia: 'https://en.wikipedia.org/wiki/Fantastic_Four:_Rise_of_the_Silver_Surfer',
      continuity: 'fox-fantastic-four',
    },
    '2008|Iron Man': {
      year: '2008',
      title: 'Iron Man',
      wikipedia: 'https://en.wikipedia.org/wiki/Iron_Man_(2008_film)',
      continuity: 'mcu',
    },
    '2008|The Incredible Hulk': {
      year: '2008',
      title: 'The Incredible Hulk',
      wikipedia: 'https://en.wikipedia.org/wiki/The_Incredible_Hulk_(film)',
      continuity: 'mcu',
    },
    '2008|Punisher: War Zone': {
      year: '2008',
      title: 'Punisher: War Zone',
      wikipedia: 'https://en.wikipedia.org/wiki/Punisher:_War_Zone',
    },
    '2008|X-Men Origins: Wolverine': {
      year: '2008',
      title: 'X-Men Origins: Wolverine',
      wikipedia: 'https://en.wikipedia.org/wiki/X-Men_Origins:_Wolverine',
      continuity: 'fox-x-men',
    },
    '2010|Iron Man 2': {
      year: '2010',
      title: 'Iron Man 2',
      wikipedia: 'https://en.wikipedia.org/wiki/Iron_Man_2',
      continuity: 'mcu',
    },
    '2011|Thor': {
      year: '2011',
      title: 'Thor',
      wikipedia: 'https://en.wikipedia.org/wiki/Thor_(film)',
      continuity: 'mcu',
    },
    '2011|X-Men: First Class': {
      year: '2011',
      title: 'X-Men: First Class',
      wikipedia: 'https://en.wikipedia.org/wiki/X-Men:_First_Class',
      continuity: 'fox-x-men',
    },
    '2011|Captain America: The First Avenger': {
      year: '2011',
      title: 'Captain America: The First Avenger',
      wikipedia: 'https://en.wikipedia.org/wiki/Captain_America:_The_First_Avenger',
      continuity: 'mcu',
    },
    '2011|Ghost Rider: Spirit of Vengeance': {
      year: '2011',
      title: 'Ghost Rider: Spirit of Vengeance',
      wikipedia: 'https://en.wikipedia.org/wiki/Ghost_Rider:_Spirit_of_Vengeance',
      continuity: 'sony-ghost-rider',
    },
    '2012|The Avengers': {
      year: '2012',
      title: 'The Avengers',
      wikipedia: 'https://en.wikipedia.org/wiki/The_Avengers_(2012_film)',
      continuity: 'mcu',
    },
    '2012|The Amazing Spider-Man': {
      year: '2012',
      title: 'The Amazing Spider-Man',
      wikipedia: 'https://en.wikipedia.org/wiki/The_Amazing_Spider-Man_(film)',
      continuity: 'amazing-spiderman',
    },
    '2013|Iron Man 3': {
      year: '2013',
      title: 'Iron Man 3',
      wikipedia: 'https://en.wikipedia.org/wiki/Iron_Man_3',
      continuity: 'mcu',
    },
    '2013|The Wolverine': {
      year: '2013',
      title: 'The Wolverine',
      wikipedia: 'https://en.wikipedia.org/wiki/The_Wolverine_(film)',
      continuity: 'fox-x-men',
    },
    '2013|Thor: The Dark World': {
      year: '2013',
      title: 'Thor: The Dark World',
      wikipedia: 'https://en.wikipedia.org/wiki/Thor:_The_Dark_World',
      continuity: 'mcu',
    },
    '2014|Captain America: The Winter Soldier': {
      year: '2014',
      title: 'Captain America: The Winter Soldier',
      wikipedia: 'https://en.wikipedia.org/wiki/Captain_America:_The_Winter_Soldier',
      continuity: 'mcu',
    },
    '2014|The Amazing Spider-Man 2': {
      year: '2014',
      title: 'The Amazing Spider-Man 2',
      wikipedia: 'https://en.wikipedia.org/wiki/The_Amazing_Spider-Man_2',
      continuity: 'amazing-spiderman',
    },
    '2014|X-Men: Days of Future Past': {
      year: '2014',
      title: 'X-Men: Days of Future Past',
      wikipedia: 'https://en.wikipedia.org/wiki/X-Men:_Days_of_Future_Past',
      continuity: 'fox-x-men',
    },
    '2014|Guardians of the Galaxy': {
      year: '2014',
      title: 'Guardians of the Galaxy',
      wikipedia: 'https://en.wikipedia.org/wiki/Guardians_of_the_Galaxy_(film)',
      continuity: 'mcu',
    },
    '2015|Avengers: Age of Ultron': {
      year: '2015',
      title: 'Avengers: Age of Ultron',
      wikipedia: 'https://en.wikipedia.org/wiki/Avengers:_Age_of_Ultron',
      continuity: 'mcu',
    },
    '2015|Ant-Man': {
      year: '2015',
      title: 'Ant-Man',
      wikipedia: 'https://en.wikipedia.org/wiki/Ant-Man_(film)',
      continuity: 'mcu',
    },
    '2015|Fantastic Four': {
      year: '2015',
      title: 'Fantastic Four',
      wikipedia: 'https://en.wikipedia.org/wiki/Fantastic_Four_(2015_film)',
    },
    '2016|Deadpool': {
      year: '2016',
      title: 'Deadpool',
      wikipedia: 'https://en.wikipedia.org/wiki/Deadpool_(film)',
      continuity: 'fox-x-men',
    },
    '2016|Captain America: Civil War': {
      year: '2016',
      title: 'Captain America: Civil War',
      wikipedia: 'https://en.wikipedia.org/wiki/Captain_America:_Civil_War',
      continuity: 'mcu',
    },
    '2016|X-Men: Apocalypse': {
      year: '2016',
      title: 'X-Men: Apocalypse',
      wikipedia: 'https://en.wikipedia.org/wiki/X-Men:_Apocalypse',
      continuity: 'fox-x-men',
    },
    '2016|Doctor Strange': {
      year: '2016',
      title: 'Doctor Strange',
      wikipedia: 'https://en.wikipedia.org/wiki/Doctor_Strange_(2016_film)',
      continuity: 'mcu',
    },
    '2017|Logan': {
      year: '2017',
      title: 'Logan',
      wikipedia: 'https://en.wikipedia.org/wiki/Logan_(film)',
      continuity: 'fox-x-men',
    },
    '2017|Guardians of the Galaxy Vol. 2': {
      year: '2017',
      title: 'Guardians of the Galaxy Vol. 2',
      wikipedia: 'https://en.wikipedia.org/wiki/Guardians_of_the_Galaxy_Vol._2',
      continuity: 'mcu',
    },
    '2017|Spider-Man: Homecoming': {
      year: '2017',
      title: 'Spider-Man: Homecoming',
      wikipedia: 'https://en.wikipedia.org/wiki/Spider-Man:_Homecoming',
      continuity: 'mcu',
    },
    '2017|Thor: Ragnarok': {
      year: '2017',
      title: 'Thor: Ragnarok',
      wikipedia: 'https://en.wikipedia.org/wiki/Thor:_Ragnarok',
      continuity: 'mcu',
    },
    '2018|Black Panther': {
      year: '2018',
      title: 'Black Panther',
      wikipedia: 'https://en.wikipedia.org/wiki/Black_Panther_(film)',
      continuity: 'mcu',
    },
    '2018|Avengers: Infinity War': {
      year: '2018',
      title: 'Avengers: Infinity War',
      wikipedia: 'https://en.wikipedia.org/wiki/Avengers:_Infinity_War',
      continuity: 'mcu',
    },
    '2018|Deadpool 2': {
      year: '2018',
      title: 'Deadpool 2',
      wikipedia: 'https://en.wikipedia.org/wiki/Deadpool_2',
      continuity: 'fox-x-men',
    },
    '2018|Ant-Man and the Wasp': {
      year: '2018',
      title: 'Ant-Man and the Wasp',
      wikipedia: 'https://en.wikipedia.org/wiki/Ant-Man_and_the_Wasp',
      continuity: 'mcu',
    },
    '2018|Venom': {
      year: '2018',
      title: 'Venom',
      wikipedia: 'https://en.wikipedia.org/wiki/Venom_(2018_film)',
      continuity: 'ssu',
    },
    '2018|Spider-Man: Into the Spider-Verse': {
      year: '2018',
      title: 'Spider-Man: Into the Spider-Verse',
      wikipedia: 'https://en.wikipedia.org/wiki/Spider-Man:_Into_the_Spider-Verse',
      continuity: 'spider-verse',
    },
    '2019|Captain Marvel': {
      year: '2019',
      title: 'Captain Marvel',
      wikipedia: 'https://en.wikipedia.org/wiki/Captain_Marvel_(film)',
      continuity: 'mcu',
    },
    '2019|Avengers: Endgame': {
      year: '2019',
      title: 'Avengers: Endgame',
      wikipedia: 'https://en.wikipedia.org/wiki/Avengers:_Endgame',
      continuity: 'mcu',
    },
    '2019|Dark Phoenix': {
      year: '2019',
      title: 'Dark Phoenix',
      wikipedia: 'https://en.wikipedia.org/wiki/Dark_Phoenix_(film)',
      continuity: 'fox-x-men',
    },
    '2019|Spider-Man: Far From Home': {
      year: '2019',
      title: 'Spider-Man: Far From Home',
      wikipedia: 'https://en.wikipedia.org/wiki/Spider-Man:_Far_From_Home',
      continuity: 'mcu',
    },
    '2020|The New Mutants': {
      year: '2020',
      title: 'The New Mutants',
      wikipedia: 'https://en.wikipedia.org/wiki/The_New_Mutants_(film)',
      continuity: 'fox-x-men',
    },
    '2021|Black Widow': {
      year: '2021',
      title: 'Black Widow',
      wikipedia: 'https://en.wikipedia.org/wiki/Black_Widow_(2021_film)',
      continuity: 'mcu',
    },
    '2021|Shang-Chi and the Legend of the Ten Rings': {
      year: '2021',
      title: 'Shang-Chi and the Legend of the Ten Rings',
      wikipedia: 'https://en.wikipedia.org/wiki/Shang-Chi_and_the_Legend_of_the_Ten_Rings',
      continuity: 'mcu',
    },
    '2021|Venom: Let There Be Carnage': {
      year: '2021',
      title: 'Venom: Let There Be Carnage',
      wikipedia: 'https://en.wikipedia.org/wiki/Venom:_Let_There_Be_Carnage',
      continuity: 'ssu',
    },
    '2021|Eternals': {
      year: '2021',
      title: 'Eternals',
      wikipedia: 'https://en.wikipedia.org/wiki/Eternals_(film)',
      continuity: 'mcu',
    },
    '2021|Spider-Man: No Way Home': {
      year: '2021',
      title: 'Spider-Man: No Way Home',
      wikipedia: 'https://en.wikipedia.org/wiki/Spider-Man:_No_Way_Home',
      continuity: 'mcu',
    },
    '2022|Morbius': {
      year: '2022',
      title: 'Morbius',
      wikipedia: 'https://en.wikipedia.org/wiki/Morbius_(film)',
      continuity: 'ssu',
    },
    '2022|Doctor Strange in the Multiverse of Madness': {
      year: '2022',
      title: 'Doctor Strange in the Multiverse of Madness',
      wikipedia: 'https://en.wikipedia.org/wiki/Doctor_Strange_in_the_Multiverse_of_Madness',
      continuity: 'mcu',
    },
    '2022|Thor: Love and Thunder': {
      year: '2022',
      title: 'Thor: Love and Thunder',
      wikipedia: 'https://en.wikipedia.org/wiki/Thor:_Love_and_Thunder',
      continuity: 'mcu',
    },
    '2022|Black Panther: Wakanda Forever': {
      year: '2022',
      title: 'Black Panther: Wakanda Forever',
      wikipedia: 'https://en.wikipedia.org/wiki/Black_Panther:_Wakanda_Forever',
      continuity: 'mcu',
    },
    '2023|Ant-Man and the Wasp: Quantumania': {
      year: '2023',
      title: 'Ant-Man and the Wasp: Quantumania',
      wikipedia: 'https://en.wikipedia.org/wiki/Ant-Man_and_the_Wasp:_Quantumania',
      continuity: 'mcu',
    },
    '2023|Guardians of the Galaxy Vol. 3': {
      year: '2023',
      title: 'Guardians of the Galaxy Vol. 3',
      wikipedia: 'https://en.wikipedia.org/wiki/Guardians_of_the_Galaxy_Vol._3',
      continuity: 'mcu',
    },
    '2023|Spider-Man: Across the Spider-Verse': {
      year: '2023',
      title: 'Spider-Man: Across the Spider-Verse',
      wikipedia: 'https://en.wikipedia.org/wiki/Spider-Man:_Across_the_Spider-Verse',
      continuity: 'spider-verse',
    },
  },
  'live-action-tv-series': {
    '2006|Blade: The Series': {
      year: '2006',
      title: 'Blade: The Series',
      wikipedia: 'https://en.wikipedia.org/wiki/Blade:_The_Series',
      numSeasons: 1,
      numEpisodes: 12,
      continuity: 'blade',
    },
    '2013–20|Agents of S.H.I.E.L.D.': {
      year: '2013–20',
      title: 'Agents of S.H.I.E.L.D.',
      wikipedia: 'https://en.wikipedia.org/wiki/Agents_of_S.H.I.E.L.D.',
      numSeasons: 7,
      numEpisodes: 136,
      continuity: 'mcu',
    },
    '2015–16|Agent Carter': {
      year: '2015–16',
      title: 'Agent Carter',
      wikipedia: 'https://en.wikipedia.org/wiki/Agent_Carter_(TV_series)',
      numSeasons: 2,
      numEpisodes: 18,
      continuity: 'mcu-netflix',
    },
    '2015–18|Daredevil': {
      year: '2015–18',
      title: 'Daredevil',
      wikipedia: 'https://en.wikipedia.org/wiki/Daredevil_(TV_series)',
      numSeasons: 3,
      numEpisodes: 39,
      continuity: 'mcu-netflix',
    },
    '2015–19|Jessica Jones': {
      year: '2015–19',
      title: 'Jessica Jones',
      wikipedia: 'https://en.wikipedia.org/wiki/Jessica_Jones_(TV_series)',
      numSeasons: 3,
      numEpisodes: 39,
      continuity: 'mcu-netflix',
    },
    '2016–18|Luke Cage': {
      year: '2016–18',
      title: 'Luke Cage',
      wikipedia: 'https://en.wikipedia.org/wiki/Luke_Cage_(TV_series)',
      numSeasons: 2,
      numEpisodes: 26,
      continuity: 'mcu-netflix',
    },
    '2017–19|Legion': {
      year: '2017–19',
      title: 'Legion',
      wikipedia: 'https://en.wikipedia.org/wiki/Legion_(TV_series)',
      numSeasons: 3,
      numEpisodes: 27,
    },
    '2017–18|Iron Fist': {
      year: '2017–18',
      title: 'Iron Fist',
      wikipedia: 'https://en.wikipedia.org/wiki/Iron_Fist_(TV_series)',
      numSeasons: 2,
      numEpisodes: 23,
      continuity: 'mcu-netflix',
    },
    '2017|The Defenders': {
      year: '2017',
      title: 'The Defenders',
      wikipedia: 'https://en.wikipedia.org/wiki/The_Defenders_(miniseries)',
      numSeasons: 1,
      numEpisodes: 8,
      continuity: 'mcu-netflix',
    },
    '2017|Inhumans': {
      year: '2017',
      title: 'Inhumans',
      wikipedia: 'https://en.wikipedia.org/wiki/Inhumans_(TV_series)',
      numSeasons: 1,
      numEpisodes: 8,
      continuity: 'mcu',
    },
    '2017–19|The Gifted': {
      year: '2017–19',
      title: 'The Gifted',
      wikipedia: 'https://en.wikipedia.org/wiki/The_Gifted_(American_TV_series)',
      numSeasons: 2,
      numEpisodes: 29,
    },
    '2017–19|The Punisher': {
      year: '2017–19',
      title: 'The Punisher',
      wikipedia: 'https://en.wikipedia.org/wiki/The_Punisher_(TV_series)',
      numSeasons: 2,
      numEpisodes: 26,
      continuity: 'mcu-netflix',
    },
    '2017–19|Runaways': {
      year: '2017–19',
      title: 'Runaways',
      wikipedia: 'https://en.wikipedia.org/wiki/Runaways_(TV_series)',
      numSeasons: 3,
      numEpisodes: 33,
      continuity: 'mcu',
    },
    '2018–19|Cloak & Dagger': {
      year: '2018–19',
      title: 'Cloak & Dagger',
      wikipedia: 'https://en.wikipedia.org/wiki/Cloak_%26_Dagger_(TV_series)',
      numSeasons: 2,
      numEpisodes: 20,
      continuity: 'mcu',
    },
    '2020|Helstrom': {
      year: '2020',
      title: 'Helstrom',
      wikipedia: 'https://en.wikipedia.org/wiki/Helstrom_(TV_series)',
      numSeasons: 1,
      numEpisodes: 10,
    },
    '2021|WandaVision': {
      year: '2021',
      title: 'WandaVision',
      wikipedia: 'https://en.wikipedia.org/wiki/WandaVision',
      numSeasons: 1,
      numEpisodes: 9,
      continuity: 'mcu',
    },
    '2021|The Falcon and the Winter Soldier': {
      year: '2021',
      title: 'The Falcon and the Winter Soldier',
      wikipedia: 'https://en.wikipedia.org/wiki/The_Falcon_and_the_Winter_Soldier',
      numSeasons: 1,
      numEpisodes: 6,
      continuity: 'mcu',
    },
    '2021|Hawkeye': {
      year: '2021',
      title: 'Hawkeye',
      wikipedia: 'https://en.wikipedia.org/wiki/Hawkeye_(2021_TV_series)',
      numSeasons: 1,
      numEpisodes: 6,
      continuity: 'mcu',
    },
    '2021–24|Loki': {
      year: '2021–24',
      title: 'Loki',
      wikipedia: 'https://en.wikipedia.org/wiki/Loki_(TV_series)',
      numSeasons: 1,
      numEpisodes: 6,
      continuity: 'mcu',
    },
    '2022|Moon Knight': {
      year: '2022',
      title: 'Moon Knight',
      wikipedia: 'https://en.wikipedia.org/wiki/Moon_Knight_(TV_series)',
      numSeasons: 1,
      numEpisodes: 6,
      continuity: 'mcu',
    },
    '2022|Ms. Marvel': {
      year: '2022',
      title: 'Ms. Marvel',
      wikipedia: 'https://en.wikipedia.org/wiki/Ms._Marvel_(TV_series)',
      numSeasons: 1,
      numEpisodes: 6,
      continuity: 'mcu',
    },
    '2022|She-Hulk: Attorney at Law': {
      year: '2022',
      title: 'She-Hulk: Attorney at Law',
      wikipedia: 'https://en.wikipedia.org/wiki/She-Hulk:_Attorney_at_Law',
      numSeasons: 1,
      numEpisodes: 9,
      continuity: 'mcu',
    },
    '2023|Secret Invasion': {
      year: '2023',
      title: 'Secret Invasion',
      wikipedia: 'https://en.wikipedia.org/wiki/Secret_Invasion_(TV_series)',
      numSeasons: 1,
      numEpisodes: 6,
      continuity: 'mcu',
    },
  },
  'animated-tv-series': {
    '1992–97|X-Men': {
      year: '1992–97',
      title: 'X-Men',
      url: 'https://en.wikipedia.org/wiki/X-Men:_The_Animated_Series',
      numSeasons: 5,
      numEpisodes: 76,
    },
    '1994–96|Fantastic Four': {
      year: '1994–96',
      title: 'Fantastic Four',
      url: 'https://en.wikipedia.org/wiki/Fantastic_Four_(1994_TV_series)',
      numSeasons: 2,
      numEpisodes: 26,
    },
    '1994–96|Iron Man': {
      year: '1994–96',
      title: 'Iron Man',
      url: 'https://en.wikipedia.org/wiki/Iron_Man_(TV_series)',
      numSeasons: 2,
      numEpisodes: 26,
    },
    '1994–98|Spider-Man': {
      year: '1994–98',
      title: 'Spider-Man',
      url: 'https://en.wikipedia.org/wiki/Spider-Man_(1994_TV_series)',
      numSeasons: 5,
      numEpisodes: 65,
    },
    '1996–97|The Incredible Hulk': {
      year: '1996–97',
      title: 'The Incredible Hulk',
      url: 'https://en.wikipedia.org/wiki/The_Incredible_Hulk_(1996_TV_series)',
      numSeasons: 2,
      numEpisodes: 21,
    },
    '1998|Silver Surfer': {
      year: '1998',
      title: 'Silver Surfer',
      url: 'https://en.wikipedia.org/wiki/Silver_Surfer_(TV_series)',
      numSeasons: 1,
      numEpisodes: 13,
    },
    '1999–2001|Spider-Man Unlimited': {
      year: '1999–2001',
      title: 'Spider-Man Unlimited',
      url: 'https://en.wikipedia.org/wiki/Spider-Man_Unlimited',
      numSeasons: 1,
      numEpisodes: 13,
    },
    '1999–2000|The Avengers: United They Stand': {
      year: '1999–2000',
      title: 'The Avengers: United They Stand',
      url: 'https://en.wikipedia.org/wiki/The_Avengers:_United_They_Stand',
      numSeasons: 1,
      numEpisodes: 13,
    },
    '2000–03|X-Men: Evolution': {
      year: '2000–03',
      title: 'X-Men: Evolution',
      url: 'https://en.wikipedia.org/wiki/X-Men:_Evolution',
      numSeasons: 4,
      numEpisodes: 52,
    },
    '2003|Spider-Man: The New Animated Series': {
      year: '2003',
      title: 'Spider-Man: The New Animated Series',
      url: 'https://en.wikipedia.org/wiki/Spider-Man:_The_New_Animated_Series',
      numSeasons: 1,
      numEpisodes: 13,
    },
    "2006–07|Fantastic Four: World's Greatest Heroes": {
      year: '2006–07',
      title: "Fantastic Four: World's Greatest Heroes",
      url: 'https://en.wikipedia.org/wiki/Fantastic_Four:_World%27s_Greatest_Heroes',
      numSeasons: 1,
      numEpisodes: 26,
    },
    '2008–09|The Spectacular Spider-Man': {
      year: '2008–09',
      title: 'The Spectacular Spider-Man',
      url: 'https://en.wikipedia.org/wiki/The_Spectacular_Spider-Man_(TV_series)',
      numSeasons: 2,
      numEpisodes: 26,
    },
    '2009|Wolverine and the X-Men': {
      year: '2009',
      title: 'Wolverine and the X-Men',
      url: 'https://en.wikipedia.org/wiki/Wolverine_and_the_X-Men_(TV_series)',
      numSeasons: 1,
      numEpisodes: 26,
    },
    '2009–12|Iron Man: Armored Adventures': {
      year: '2009–12',
      title: 'Iron Man: Armored Adventures',
      url: 'https://en.wikipedia.org/wiki/Iron_Man:_Armored_Adventures',
      numSeasons: 2,
      numEpisodes: 52,
    },
    '2009–11|The Super Hero Squad Show': {
      year: '2009–11',
      title: 'The Super Hero Squad Show',
      url: 'https://en.wikipedia.org/wiki/The_Super_Hero_Squad_Show',
      numSeasons: 2,
      numEpisodes: 52,
    },
    "2010–12|The Avengers: Earth's Mightiest Heroes": {
      year: '2010–12',
      title: "The Avengers: Earth's Mightiest Heroes",
      url: 'https://en.wikipedia.org/wiki/The_Avengers:_Earth%27s_Mightiest_Heroes',
      numSeasons: 2,
      numEpisodes: 52,
    },
    '2010–11|Marvel Anime: Iron Man': {
      year: '2010–11',
      title: 'Marvel Anime: Iron Man',
      url: 'https://en.wikipedia.org/wiki/Marvel_Anime#Iron_Man',
      numSeasons: 1,
      numEpisodes: 12,
      isAnime: 'yes',
    },
    '2011–12|Marvel Anime: Wolverine': {
      year: '2011–12',
      title: 'Marvel Anime: Wolverine',
      url: 'https://en.wikipedia.org/wiki/Marvel_Anime#Wolverine',
      numSeasons: 1,
      numEpisodes: 12,
      isAnime: 'yes',
    },
    '2011–12|Marvel Anime: X-Men': {
      year: '2011–12',
      title: 'Marvel Anime: X-Men',
      url: 'https://en.wikipedia.org/wiki/Marvel_Anime#X-Men',
      numSeasons: 1,
      numEpisodes: 12,
      isAnime: 'yes',
    },
    '2011–12|Marvel Anime: Blade': {
      year: '2011–12',
      title: 'Marvel Anime: Blade',
      url: 'https://en.wikipedia.org/wiki/Marvel_Anime#Blade',
      numSeasons: 1,
      numEpisodes: 12,
      isAnime: 'yes',
    },
    '2012–17|Ultimate Spider-Man': {
      year: '2012–17',
      title: 'Ultimate Spider-Man',
      url: 'https://en.wikipedia.org/wiki/Ultimate_Spider-Man_(TV_series)',
      numSeasons: 4,
      numEpisodes: 104,
    },
    '2013–19|Avengers Assemble': {
      year: '2013–19',
      title: 'Avengers Assemble',
      url: 'https://en.wikipedia.org/wiki/Avengers_Assemble_(TV_series)',
      numSeasons: 5,
      numEpisodes: 127,
    },
    '2013–15|Hulk and the Agents of S.M.A.S.H.': {
      year: '2013–15',
      title: 'Hulk and the Agents of S.M.A.S.H.',
      url: 'https://en.wikipedia.org/wiki/Hulk_and_the_Agents_of_S.M.A.S.H.',
      numSeasons: 2,
      numEpisodes: 52,
    },
    '2015–16|Marvel Disk Wars: The Avengers': {
      year: '2015–16',
      title: 'Marvel Disk Wars: The Avengers',
      url: 'https://en.wikipedia.org/wiki/Marvel_Disk_Wars:_The_Avengers',
      numSeasons: 1,
      numEpisodes: 51,
      isAnime: 'yes',
    },
    '2015–19|Guardians of the Galaxy': {
      year: '2015–19',
      title: 'Guardians of the Galaxy',
      url: 'https://en.wikipedia.org/wiki/Guardians_of_the_Galaxy_(TV_series)',
      numSeasons: 3,
      numEpisodes: 79,
    },
    '2017–18|Marvel Future Avengers': {
      year: '2017–18',
      title: 'Marvel Future Avengers',
      url: 'https://en.wikipedia.org/wiki/Marvel_Future_Avengers',
      numSeasons: 2,
      numEpisodes: 39,
      isAnime: 'yes',
    },
    "2017–20|Marvel's Spider-Man": {
      year: '2017–20',
      title: "Marvel's Spider-Man",
      url: 'https://en.wikipedia.org/wiki/Spider-Man_(2017_TV_series)',
      numSeasons: 3,
      numEpisodes: 58,
    },
    '2021|M.O.D.O.K.': {
      year: '2021',
      title: 'M.O.D.O.K.',
      url: 'https://en.wikipedia.org/wiki/M.O.D.O.K._(TV_series)',
      numSeasons: 1,
      numEpisodes: 10,
    },
    '2021–2023|Spidey and His Amazing Friends': {
      year: '2021–2023',
      title: 'Spidey and His Amazing Friends',
      url: 'https://en.wikipedia.org/wiki/Spidey_and_His_Amazing_Friends_(2021_TV_series)',
      numSeasons: 2,
      numEpisodes: 47,
    },
    '2021|Hit-Monkey': {
      year: '2021',
      title: 'Hit-Monkey',
      url: 'https://en.wikipedia.org/wiki/Hit-Monkey_(TV_series)',
      numSeasons: 1,
      numEpisodes: 10,
    },
    '2023|Moon Girl and Devil Dinosaur': {
      year: '2023',
      title: 'Moon Girl and Devil Dinosaur',
      url: 'https://en.wikipedia.org/wiki/Moon_Girl_and_Devil_Dinosaur',
      numSeasons: 1,
      numEpisodes: 17,
    },
  },
} as const;
