export const allTitles = {
  'movies': [
    {
      year: '1998',
      title: 'Blade',
      wikipedia: 'https://en.wikipedia.org/wiki/Blade_(1998_film)',
      continuity: 'blade',
    },
    {
      year: '2000',
      title: 'X-Men',
      wikipedia: 'https://en.wikipedia.org/wiki/X-Men_(film)',
      continuity: 'fox-x-men',
    },
    {
      year: '2002',
      title: 'Blade II',
      wikipedia: 'https://en.wikipedia.org/wiki/Blade_II',
      continuity: 'blade',
    },
    {
      year: '2002',
      title: 'Spider-Man',
      wikipedia: 'https://en.wikipedia.org/wiki/Spider-Man_(2002_film)',
      continuity: 'tobey-spiderman',
    },
    {
      year: '2003',
      title: 'Daredevil',
      wikipedia: 'https://en.wikipedia.org/wiki/Daredevil_(film)',
      continuity: 'fox-daredevil',
    },
    {
      year: '2003',
      title: 'X2',
      wikipedia: 'https://en.wikipedia.org/wiki/X2_(film)',
      continuity: 'fox-x-men',
    },
    { year: '2003', title: 'Hulk', wikipedia: 'https://en.wikipedia.org/wiki/Hulk_(film)' },
    {
      year: '2004',
      title: 'The Punisher',
      wikipedia: 'https://en.wikipedia.org/wiki/The_Punisher_(2004_film)',
    },
    {
      year: '2004',
      title: 'Spider-Man 2',
      wikipedia: 'https://en.wikipedia.org/wiki/Spider-Man_2',
      continuity: 'tobey-spiderman',
    },
    {
      year: '2004',
      title: 'Blade: Trinity',
      wikipedia: 'https://en.wikipedia.org/wiki/Blade:_Trinity',
      continuity: 'blade',
    },
    {
      year: '2005',
      title: 'Elektra',
      wikipedia: 'https://en.wikipedia.org/wiki/Elektra_(2005_film)',
      continuity: 'fox-daredevil',
    },
    {
      year: '2005',
      title: 'Fantastic Four',
      wikipedia: 'https://en.wikipedia.org/wiki/Fantastic_Four_(2005_film)',
      continuity: 'fox-fantastic-four',
    },
    {
      year: '2006',
      title: 'X-Men: The Last Stand',
      wikipedia: 'https://en.wikipedia.org/wiki/X-Men:_The_Last_Stand',
      continuity: 'fox-x-men',
    },
    {
      year: '2007',
      title: 'Ghost Rider',
      wikipedia: 'https://en.wikipedia.org/wiki/Ghost_Rider_(2007_film)',
      continuity: 'sony-ghost-rider',
    },
    {
      year: '2007',
      title: 'Spider-Man 3',
      wikipedia: 'https://en.wikipedia.org/wiki/Spider-Man_3',
      continuity: 'tobey-spiderman',
    },
    {
      year: '2007',
      title: 'Fantastic Four: Rise of the Silver Surfer',
      wikipedia: 'https://en.wikipedia.org/wiki/Fantastic_Four:_Rise_of_the_Silver_Surfer',
      continuity: 'fox-fantastic-four',
    },
    {
      year: '2008',
      title: 'Iron Man',
      wikipedia: 'https://en.wikipedia.org/wiki/Iron_Man_(2008_film)',
      continuity: 'mcu',
    },
    {
      year: '2008',
      title: 'The Incredible Hulk',
      wikipedia: 'https://en.wikipedia.org/wiki/The_Incredible_Hulk_(film)',
      continuity: 'mcu',
    },
    {
      year: '2008',
      title: 'Punisher: War Zone',
      wikipedia: 'https://en.wikipedia.org/wiki/Punisher:_War_Zone',
    },
    {
      year: '2008',
      title: 'X-Men Origins: Wolverine',
      wikipedia: 'https://en.wikipedia.org/wiki/X-Men_Origins:_Wolverine',
      continuity: 'fox-x-men',
    },
    {
      year: '2010',
      title: 'Iron Man 2',
      wikipedia: 'https://en.wikipedia.org/wiki/Iron_Man_2',
      continuity: 'mcu',
    },
    {
      year: '2011',
      title: 'Thor',
      wikipedia: 'https://en.wikipedia.org/wiki/Thor_(film)',
      continuity: 'mcu',
    },
    {
      year: '2011',
      title: 'X-Men: First Class',
      wikipedia: 'https://en.wikipedia.org/wiki/X-Men:_First_Class',
      continuity: 'fox-x-men',
    },
    {
      year: '2011',
      title: 'Captain America: The First Avenger',
      wikipedia: 'https://en.wikipedia.org/wiki/Captain_America:_The_First_Avenger',
      continuity: 'mcu',
    },
    {
      year: '2011',
      title: 'Ghost Rider: Spirit of Vengeance',
      wikipedia: 'https://en.wikipedia.org/wiki/Ghost_Rider:_Spirit_of_Vengeance',
      continuity: 'sony-ghost-rider',
    },
    {
      year: '2012',
      title: 'The Avengers',
      wikipedia: 'https://en.wikipedia.org/wiki/The_Avengers_(2012_film)',
      continuity: 'mcu',
    },
    {
      year: '2012',
      title: 'The Amazing Spider-Man',
      wikipedia: 'https://en.wikipedia.org/wiki/The_Amazing_Spider-Man_(film)',
      continuity: 'amazing-spiderman',
    },
    {
      year: '2013',
      title: 'Iron Man 3',
      wikipedia: 'https://en.wikipedia.org/wiki/Iron_Man_3',
      continuity: 'mcu',
    },
    {
      year: '2013',
      title: 'The Wolverine',
      wikipedia: 'https://en.wikipedia.org/wiki/The_Wolverine_(film)',
      continuity: 'fox-x-men',
    },
    {
      year: '2013',
      title: 'Thor: The Dark World',
      wikipedia: 'https://en.wikipedia.org/wiki/Thor:_The_Dark_World',
      continuity: 'mcu',
    },
    {
      year: '2014',
      title: 'Captain America: The Winter Soldier',
      wikipedia: 'https://en.wikipedia.org/wiki/Captain_America:_The_Winter_Soldier',
      continuity: 'mcu',
    },
    {
      year: '2014',
      title: 'The Amazing Spider-Man 2',
      wikipedia: 'https://en.wikipedia.org/wiki/The_Amazing_Spider-Man_2',
      continuity: 'amazing-spiderman',
    },
    {
      year: '2014',
      title: 'X-Men: Days of Future Past',
      wikipedia: 'https://en.wikipedia.org/wiki/X-Men:_Days_of_Future_Past',
      continuity: 'fox-x-men',
    },
    {
      year: '2014',
      title: 'Guardians of the Galaxy',
      wikipedia: 'https://en.wikipedia.org/wiki/Guardians_of_the_Galaxy_(film)',
      continuity: 'mcu',
    },
    {
      year: '2015',
      title: 'Avengers: Age of Ultron',
      wikipedia: 'https://en.wikipedia.org/wiki/Avengers:_Age_of_Ultron',
      continuity: 'mcu',
    },
    {
      year: '2015',
      title: 'Ant-Man',
      wikipedia: 'https://en.wikipedia.org/wiki/Ant-Man_(film)',
      continuity: 'mcu',
    },
    {
      year: '2015',
      title: 'Fantastic Four',
      wikipedia: 'https://en.wikipedia.org/wiki/Fantastic_Four_(2015_film)',
    },
    {
      year: '2016',
      title: 'Deadpool',
      wikipedia: 'https://en.wikipedia.org/wiki/Deadpool_(film)',
      continuity: 'fox-x-men',
    },
    {
      year: '2016',
      title: 'Captain America: Civil War',
      wikipedia: 'https://en.wikipedia.org/wiki/Captain_America:_Civil_War',
      continuity: 'mcu',
    },
    {
      year: '2016',
      title: 'X-Men: Apocalypse',
      wikipedia: 'https://en.wikipedia.org/wiki/X-Men:_Apocalypse',
      continuity: 'fox-x-men',
    },
    {
      year: '2016',
      title: 'Doctor Strange',
      wikipedia: 'https://en.wikipedia.org/wiki/Doctor_Strange_(2016_film)',
      continuity: 'mcu',
    },
    {
      year: '2017',
      title: 'Logan',
      wikipedia: 'https://en.wikipedia.org/wiki/Logan_(film)',
      continuity: 'fox-x-men',
    },
    {
      year: '2017',
      title: 'Guardians of the Galaxy Vol. 2',
      wikipedia: 'https://en.wikipedia.org/wiki/Guardians_of_the_Galaxy_Vol._2',
      continuity: 'mcu',
    },
    {
      year: '2017',
      title: 'Spider-Man: Homecoming',
      wikipedia: 'https://en.wikipedia.org/wiki/Spider-Man:_Homecoming',
      continuity: 'mcu',
    },
    {
      year: '2017',
      title: 'Thor: Ragnarok',
      wikipedia: 'https://en.wikipedia.org/wiki/Thor:_Ragnarok',
      continuity: 'mcu',
    },
    {
      year: '2018',
      title: 'Black Panther',
      wikipedia: 'https://en.wikipedia.org/wiki/Black_Panther_(film)',
      continuity: 'mcu',
    },
    {
      year: '2018',
      title: 'Avengers: Infinity War',
      wikipedia: 'https://en.wikipedia.org/wiki/Avengers:_Infinity_War',
      continuity: 'mcu',
    },
    {
      year: '2018',
      title: 'Deadpool 2',
      wikipedia: 'https://en.wikipedia.org/wiki/Deadpool_2',
      continuity: 'fox-x-men',
    },
    {
      year: '2018',
      title: 'Ant-Man and the Wasp',
      wikipedia: 'https://en.wikipedia.org/wiki/Ant-Man_and_the_Wasp',
      continuity: 'mcu',
    },
    {
      year: '2018',
      title: 'Venom',
      wikipedia: 'https://en.wikipedia.org/wiki/Venom_(2018_film)',
      continuity: 'ssu',
    },
    {
      year: '2019',
      title: 'Captain Marvel',
      wikipedia: 'https://en.wikipedia.org/wiki/Captain_Marvel_(film)',
      continuity: 'mcu',
    },
    {
      year: '2019',
      title: 'Avengers: Endgame',
      wikipedia: 'https://en.wikipedia.org/wiki/Avengers:_Endgame',
      continuity: 'mcu',
    },
    {
      year: '2019',
      title: 'Dark Phoenix',
      wikipedia: 'https://en.wikipedia.org/wiki/Dark_Phoenix_(film)',
      continuity: 'fox-x-men',
    },
    {
      year: '2019',
      title: 'Spider-Man: Far From Home',
      wikipedia: 'https://en.wikipedia.org/wiki/Spider-Man:_Far_From_Home',
      continuity: 'mcu',
    },
    {
      year: '2020',
      title: 'The New Mutants',
      wikipedia: 'https://en.wikipedia.org/wiki/The_New_Mutants_(film)',
      continuity: 'fox-x-men',
    },
    {
      year: '2021',
      title: 'Black Widow',
      wikipedia: 'https://en.wikipedia.org/wiki/Black_Widow_(2021_film)',
      continuity: 'mcu',
    },
    {
      year: '2021',
      title: 'Shang-Chi and the Legend of the Ten Rings',
      wikipedia: 'https://en.wikipedia.org/wiki/Shang-Chi_and_the_Legend_of_the_Ten_Rings',
      continuity: 'mcu',
    },
    {
      year: '2021',
      title: 'Venom: Let There Be Carnage',
      wikipedia: 'https://en.wikipedia.org/wiki/Venom:_Let_There_Be_Carnage',
      continuity: 'ssu',
    },
    {
      year: '2021',
      title: 'Eternals',
      wikipedia: 'https://en.wikipedia.org/wiki/Eternals_(film)',
      continuity: 'mcu',
    },
    {
      year: '2021',
      title: 'Spider-Man: No Way Home',
      wikipedia: 'https://en.wikipedia.org/wiki/Spider-Man:_No_Way_Home',
      continuity: 'mcu',
    },
    {
      year: '2022',
      title: 'Morbius',
      wikipedia: 'https://en.wikipedia.org/wiki/Morbius_(film)',
      continuity: 'ssu',
    },
    {
      year: '2022',
      title: 'Doctor Strange in the Multiverse of Madness',
      wikipedia: 'https://en.wikipedia.org/wiki/Doctor_Strange_in_the_Multiverse_of_Madness',
      continuity: 'mcu',
    },
    {
      year: '2022',
      title: 'Thor: Love and Thunder',
      wikipedia: 'https://en.wikipedia.org/wiki/Thor:_Love_and_Thunder',
      continuity: 'mcu',
    },
    {
      year: '2022',
      title: 'Black Panther: Wakanda Forever',
      wikipedia: 'https://en.wikipedia.org/wiki/Black_Panther:_Wakanda_Forever',
      continuity: 'mcu',
    },
    {
      year: '2023',
      title: 'Ant-Man and the Wasp: Quantumania',
      wikipedia: 'https://en.wikipedia.org/wiki/Ant-Man_and_the_Wasp:_Quantumania',
      continuity: 'mcu',
    },
    {
      year: '2023',
      title: 'Guardians of the Galaxy Vol. 3',
      wikipedia: 'https://en.wikipedia.org/wiki/Guardians_of_the_Galaxy_Vol._3',
      continuity: 'mcu',
    },
  ],
  'live-action-tv-series': [
    {
      year: '2006',
      title: 'Blade: The Series',
      wikipedia: 'https://en.wikipedia.org/wiki/Blade:_The_Series',
      numSeasons: 1,
      numEpisodes: 12,
      continuity: 'blade',
    },
    {
      year: '2013–20',
      title: 'Agents of S.H.I.E.L.D.',
      wikipedia: 'https://en.wikipedia.org/wiki/Agents_of_S.H.I.E.L.D.',
      numSeasons: 7,
      numEpisodes: 136,
      mcu: 1,
      continuity: 'mcu',
    },
    {
      year: '2015–16',
      title: 'Agent Carter',
      wikipedia: 'https://en.wikipedia.org/wiki/Agent_Carter_(TV_series)',
      numSeasons: 2,
      numEpisodes: 18,
      mcu: 1,
      continuity: 'mcu',
    },
    {
      year: '2015–18',
      title: 'Daredevil',
      wikipedia: 'https://en.wikipedia.org/wiki/Daredevil_(TV_series)',
      numSeasons: 3,
      numEpisodes: 39,
      mcu: 1,
      continuity: 'mcu',
    },
    {
      year: '2015–19',
      title: 'Jessica Jones',
      wikipedia: 'https://en.wikipedia.org/wiki/Jessica_Jones_(TV_series)',
      numSeasons: 3,
      numEpisodes: 39,
      mcu: 1,
      continuity: 'mcu',
    },
    {
      year: '2016–18',
      title: 'Luke Cage',
      wikipedia: 'https://en.wikipedia.org/wiki/Luke_Cage_(TV_series)',
      numSeasons: 2,
      numEpisodes: 26,
      mcu: 1,
      continuity: 'mcu',
    },
    {
      year: '2017–19',
      title: 'Legion',
      wikipedia: 'https://en.wikipedia.org/wiki/Legion_(TV_series)',
      numSeasons: 3,
      numEpisodes: 27,
    },
    {
      year: '2017–18',
      title: 'Iron Fist',
      wikipedia: 'https://en.wikipedia.org/wiki/Iron_Fist_(TV_series)',
      numSeasons: 2,
      numEpisodes: 23,
      mcu: 1,
      continuity: 'mcu',
    },
    {
      year: '2017',
      title: 'The Defenders',
      wikipedia: 'https://en.wikipedia.org/wiki/The_Defenders_(miniseries)',
      numSeasons: 1,
      numEpisodes: 8,
      mcu: 1,
      continuity: 'mcu',
    },
    {
      year: '2017',
      title: 'Inhumans',
      wikipedia: 'https://en.wikipedia.org/wiki/Inhumans_(TV_series)',
      numSeasons: 1,
      numEpisodes: 8,
      mcu: 1,
      continuity: 'mcu',
    },
    {
      year: '2017–19',
      title: 'The Gifted',
      wikipedia: 'https://en.wikipedia.org/wiki/The_Gifted_(American_TV_series)',
      numSeasons: 2,
      numEpisodes: 29,
    },
    {
      year: '2017–19',
      title: 'The Punisher',
      wikipedia: 'https://en.wikipedia.org/wiki/The_Punisher_(TV_series)',
      numSeasons: 2,
      numEpisodes: 26,
      mcu: 1,
      continuity: 'mcu',
    },
    {
      year: '2017–19',
      title: 'Runaways',
      wikipedia: 'https://en.wikipedia.org/wiki/Runaways_(TV_series)',
      numSeasons: 3,
      numEpisodes: 33,
      mcu: 1,
      continuity: 'mcu',
    },
    {
      year: '2018–19',
      title: 'Cloak & Dagger',
      wikipedia: 'https://en.wikipedia.org/wiki/Cloak_%26_Dagger_(TV_series)',
      numSeasons: 2,
      numEpisodes: 20,
      mcu: 1,
      continuity: 'mcu',
    },
    {
      year: '2020',
      title: 'Helstrom',
      wikipedia: 'https://en.wikipedia.org/wiki/Helstrom_(TV_series)',
      numSeasons: 1,
      numEpisodes: 10,
    },
    {
      year: '2021',
      title: 'WandaVision',
      wikipedia: 'https://en.wikipedia.org/wiki/WandaVision',
      numSeasons: 1,
      numEpisodes: 9,
      mcu: 1,
      continuity: 'mcu',
    },
    {
      year: '2021',
      title: 'The Falcon and the Winter Soldier',
      wikipedia: 'https://en.wikipedia.org/wiki/The_Falcon_and_the_Winter_Soldier',
      numSeasons: 1,
      numEpisodes: 6,
      mcu: 1,
      continuity: 'mcu',
    },
    {
      year: '2021',
      title: 'Hawkeye',
      wikipedia: 'https://en.wikipedia.org/wiki/Hawkeye_(2021_TV_series)',
      numSeasons: 1,
      numEpisodes: 6,
      mcu: 1,
      continuity: 'mcu',
    },
    {
      year: '2021–24',
      title: 'Loki',
      wikipedia: 'https://en.wikipedia.org/wiki/Loki_(TV_series)',
      numSeasons: 1,
      numEpisodes: 6,
      mcu: 1,
      continuity: 'mcu',
    },
    {
      year: '2022',
      title: 'Moon Knight',
      wikipedia: 'https://en.wikipedia.org/wiki/Moon_Knight_(TV_series)',
      numSeasons: 1,
      numEpisodes: 6,
      mcu: 1,
      continuity: 'mcu',
    },
    {
      year: '2022',
      title: 'Ms. Marvel',
      wikipedia: 'https://en.wikipedia.org/wiki/Ms._Marvel_(TV_series)',
      numSeasons: 1,
      numEpisodes: 6,
      mcu: 1,
      continuity: 'mcu',
    },
    {
      year: '2022',
      title: 'She-Hulk: Attorney at Law',
      wikipedia: 'https://en.wikipedia.org/wiki/She-Hulk:_Attorney_at_Law',
      numSeasons: 1,
      numEpisodes: 9,
      mcu: 1,
      continuity: 'mcu',
    },
    {
      year: '2023',
      title: 'Secret Invasion',
      wikipedia: 'https://en.wikipedia.org/wiki/Secret_Invasion_(TV_series)',
      numSeasons: 1,
      numEpisodes: 6,
      continuity: 'mcu',
    },
  ],
  'animated-tv-series': [
    {
      year: '1992–97',
      title: 'X-Men',
      url: 'https://en.wikipedia.org/wiki/X-Men:_The_Animated_Series',
      numSeasons: 5,
      numEpisodes: 76,
    },
    {
      year: '1994–96',
      title: 'Fantastic Four',
      url: 'https://en.wikipedia.org/wiki/Fantastic_Four_(1994_TV_series)',
      numSeasons: 2,
      numEpisodes: 26,
    },
    {
      year: '1994–96',
      title: 'Iron Man',
      url: 'https://en.wikipedia.org/wiki/Iron_Man_(TV_series)',
      numSeasons: 2,
      numEpisodes: 26,
    },
    {
      year: '1994–98',
      title: 'Spider-Man',
      url: 'https://en.wikipedia.org/wiki/Spider-Man_(1994_TV_series)',
      numSeasons: 5,
      numEpisodes: 65,
    },
    {
      year: '1996–97',
      title: 'The Incredible Hulk',
      url: 'https://en.wikipedia.org/wiki/The_Incredible_Hulk_(1996_TV_series)',
      numSeasons: 2,
      numEpisodes: 21,
    },
    {
      year: '1998',
      title: 'Silver Surfer',
      url: 'https://en.wikipedia.org/wiki/Silver_Surfer_(TV_series)',
      numSeasons: 1,
      numEpisodes: 13,
    },
    {
      year: '1999–2001',
      title: 'Spider-Man Unlimited',
      url: 'https://en.wikipedia.org/wiki/Spider-Man_Unlimited',
      numSeasons: 1,
      numEpisodes: 13,
    },
    {
      year: '1999–2000',
      title: 'The Avengers: United They Stand',
      url: 'https://en.wikipedia.org/wiki/The_Avengers:_United_They_Stand',
      numSeasons: 1,
      numEpisodes: 13,
    },
    {
      year: '2000–03',
      title: 'X-Men: Evolution',
      url: 'https://en.wikipedia.org/wiki/X-Men:_Evolution',
      numSeasons: 4,
      numEpisodes: 52,
    },
    {
      year: '2003',
      title: 'Spider-Man: The New Animated Series',
      url: 'https://en.wikipedia.org/wiki/Spider-Man:_The_New_Animated_Series',
      numSeasons: 1,
      numEpisodes: 13,
    },
    {
      year: '2006–07',
      title: "Fantastic Four: World's Greatest Heroes",
      url: 'https://en.wikipedia.org/wiki/Fantastic_Four:_World%27s_Greatest_Heroes',
      numSeasons: 1,
      numEpisodes: 26,
    },
    {
      year: '2008–09',
      title: 'The Spectacular Spider-Man',
      url: 'https://en.wikipedia.org/wiki/The_Spectacular_Spider-Man_(TV_series)',
      numSeasons: 2,
      numEpisodes: 26,
    },
    {
      year: '2009',
      title: 'Wolverine and the X-Men',
      url: 'https://en.wikipedia.org/wiki/Wolverine_and_the_X-Men_(TV_series)',
      numSeasons: 1,
      numEpisodes: 26,
    },
    {
      year: '2009–12',
      title: 'Iron Man: Armored Adventures',
      url: 'https://en.wikipedia.org/wiki/Iron_Man:_Armored_Adventures',
      numSeasons: 2,
      numEpisodes: 52,
    },
    {
      year: '2009–11',
      title: 'The Super Hero Squad Show',
      url: 'https://en.wikipedia.org/wiki/The_Super_Hero_Squad_Show',
      numSeasons: 2,
      numEpisodes: 52,
    },
    {
      year: '2010–12',
      title: "The Avengers: Earth's Mightiest Heroes",
      url: 'https://en.wikipedia.org/wiki/The_Avengers:_Earth%27s_Mightiest_Heroes',
      numSeasons: 2,
      numEpisodes: 52,
    },
    {
      year: '2010–11',
      title: 'Marvel Anime: Iron Man',
      url: 'https://en.wikipedia.org/wiki/Marvel_Anime#Iron_Man',
      numSeasons: 1,
      numEpisodes: 12,
      isAnime: 'yes',
    },
    {
      year: '2011–12',
      title: 'Marvel Anime: Wolverine',
      url: 'https://en.wikipedia.org/wiki/Marvel_Anime#Wolverine',
      numSeasons: 1,
      numEpisodes: 12,
      isAnime: 'yes',
    },
    {
      year: '2011–12',
      title: 'Marvel Anime: X-Men',
      url: 'https://en.wikipedia.org/wiki/Marvel_Anime#X-Men',
      numSeasons: 1,
      numEpisodes: 12,
      isAnime: 'yes',
    },
    {
      year: '2011–12',
      title: 'Marvel Anime: Blade',
      url: 'https://en.wikipedia.org/wiki/Marvel_Anime#Blade',
      numSeasons: 1,
      numEpisodes: 12,
      isAnime: 'yes',
    },
    {
      year: '2012–17',
      title: 'Ultimate Spider-Man',
      url: 'https://en.wikipedia.org/wiki/Ultimate_Spider-Man_(TV_series)',
      numSeasons: 4,
      numEpisodes: 104,
    },
    {
      year: '2013–19',
      title: 'Avengers Assemble',
      url: 'https://en.wikipedia.org/wiki/Avengers_Assemble_(TV_series)',
      numSeasons: 5,
      numEpisodes: 127,
    },
    {
      year: '2013–15',
      title: 'Hulk and the Agents of S.M.A.S.H.',
      url: 'https://en.wikipedia.org/wiki/Hulk_and_the_Agents_of_S.M.A.S.H.',
      numSeasons: 2,
      numEpisodes: 52,
    },
    {
      year: '2015–16',
      title: 'Marvel Disk Wars: The Avengers',
      url: 'https://en.wikipedia.org/wiki/Marvel_Disk_Wars:_The_Avengers',
      numSeasons: 1,
      numEpisodes: 51,
      isAnime: 'yes',
    },
    {
      year: '2015–19',
      title: 'Guardians of the Galaxy',
      url: 'https://en.wikipedia.org/wiki/Guardians_of_the_Galaxy_(TV_series)',
      numSeasons: 3,
      numEpisodes: 79,
    },
    {
      year: '2017–18',
      title: 'Marvel Future Avengers',
      url: 'https://en.wikipedia.org/wiki/Marvel_Future_Avengers',
      numSeasons: 2,
      numEpisodes: 39,
      isAnime: 'yes',
    },
    {
      year: '2017–20',
      title: "Marvel's Spider-Man",
      url: 'https://en.wikipedia.org/wiki/Spider-Man_(2017_TV_series)',
      numSeasons: 3,
      numEpisodes: 58,
    },
    {
      year: '2021',
      title: 'M.O.D.O.K.',
      url: 'https://en.wikipedia.org/wiki/M.O.D.O.K._(TV_series)',
      numSeasons: 1,
      numEpisodes: 10,
    },
    {
      year: '2021–2023',
      title: 'Spidey and His Amazing Friends',
      url: 'https://en.wikipedia.org/wiki/Spidey_and_His_Amazing_Friends_(2021_TV_series)',
      numSeasons: 2,
      numEpisodes: 47,
    },
    {
      year: '2021',
      title: 'Hit-Monkey',
      url: 'https://en.wikipedia.org/wiki/Hit-Monkey_(TV_series)',
      numSeasons: 1,
      numEpisodes: 10,
    },
    {
      year: '2023',
      title: 'Moon Girl and Devil Dinosaur',
      url: 'https://en.wikipedia.org/wiki/Moon_Girl_and_Devil_Dinosaur',
      numSeasons: 1,
      numEpisodes: 17,
    },
  ],
} as const;
